apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ include "pgadmin.fullname" . }}-data'
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
