apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secrets
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    avp.kubernetes.io/path: kv/data/lab/pgadmin
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: "<PGADMIN_DEFAULT_EMAIL>"
  PGADMIN_DEFAULT_PASSWORD: "<PGADMIN_DEFAULT_PASSWORD>"
