apiVersion: v1
kind: PersistentVolume
metadata:
  name: big-chonk-srv-prod
  labels:
    storage.k8s.io/name: nfs
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/big-chonk/srv-prod-01
    server: truenas.lab
    readOnly: false
