apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{- include "affine.fullname" . }}-config'
  labels:
    {{- include "affine.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{- include "affine.fullname" . }}-storage'
  labels:
    {{- include "affine.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
