apiVersion: v1
kind: Secret
metadata:
  name: '{{- include "affine.fullname" . }}-secrets'
  labels:
    {{- include "affine.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
    avp.kubernetes.io/path: kv/data/lab/affine
stringData:
  POSTGRESQL_PASSWORD: "<POSTGRESQL_PASSWORD>"
  DATABASE_URL: "postgres://{{ .Values.postgresql.auth.username }}:<path:kv/data/lab/affine#POSTGRESQL_PASSWORD>@{{ .Release.Name }}-postgresql-hl:5432/{{ .Values.postgresql.auth.database }}"
  REDIS_SERVER_HOST: "{{ .Release.Name }}-redis-headless"
