apiVersion: v1
kind: ConfigMap
metadata:
  name: tandoor-configmap
  namespace: tandoor
  labels:
    {{- include "tandoor.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  POSTGRES_HOST: "postgres-postgresql"
  POSTGRES_PORT: "5432"
  DB_ENGINE: "django.db.backends.postgresql"
  TANDOOR_PORT: "8080"
