apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init-wait-db
  labels:
    {{- include "tandoor.labels" . | nindent 4 }}
  namespace: tandoor
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-init-wait-db
      labels:
        {{- include "tandoor.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: init-wait-db
          image: bitnami/postgresql:16.1.0-debian-11-r17
          envFrom:
            - secretRef:
                name: tandoor-secrets
            - configMapRef:
                name: tandoor-configmap
          command:
            - /bin/sh
            - -c
            - >
              until pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -h $POSTGRES_HOST; do
              echo "Waiting for database...";
              sleep 3;
              done;
