apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-media
  labels:
    {{- include "tandoor.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: 4Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-static
  labels:
    {{- include "tandoor.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: 4Gi
  accessModes:
    - ReadWriteOnce
