repositories:
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/
  - name: coredns
    url: https://coredns.github.io/helm/

releases:
  - name: metrics-server
    namespace: kube-system
    chart: metrics-server/metrics-server
    version: 3.12.2
    values: [ metrics-server.yaml ]
  - name: coredns
    namespace: kube-system
    chart: coredns/coredns
    version: 1.39.1
    values: [ coredns.yaml ]
