apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ include "invoice-builder.fullname" . }}-data'
  labels:
    {{ include "invoice-builder.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
