version: 3

vars:
  SHORT_SHA:
    sh: git rev-parse --short HEAD

dotenv:
  - ./gitea/.env

tasks:
  setup-k8s:
    desc: Run first-time K8s & core infra setup
    dir: ansible
    cmds:
      - task: bootstrap-vms
      - task: setup-k8s-master
      - task: setup-k8s-workers
      - task: setup-traefik
      - task: setup-argocd

  bootstrap-vms:
    desc: Install pre-requisites in VMs
    internal: true
    dir: ansible
    cmds:
      - ansible-playbook -i inventory/hosts playbooks/setup-vm.yml

  setup-k8s-master:
    internal: true
    desc: Setup K8s master node
    dir: ansible
    cmds:
      - ansible-playbook -i inventory/hosts playbooks/setup-k8s-master.yml

  setup-k8s-workers:
    internal: true
    desc: Setup K8s worker nodes
    dir: ansible
    cmds:
      - ansible-playbook -i inventory/hosts playbooks/setup-k8s-workers.yml

  setup-init:
    desc: Initial setup
    cmds:
      - pre-commit install
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm repo add traefik https://traefik.github.io/charts
      - helm repo add gitea https://dl.gitea.com/charts/
      - helm repo add nextcloud https://nextcloud.github.io/helm/
      - helm repo add hashicorp https://helm.releases.hashicorp.com
      - helm repo add firefly https://firefly-iii.github.io/kubernetes/
      - helm repo add jameswynn https://jameswynn.github.io/helm-charts
      - helm repo add portainer https://portainer.github.io/k8s/
      - helm repo add secrets-store-csi-driver https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
      - helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
      - helm repo add minio-operator https://operator.min.io
      - helm repo update

  setup-traefik:
    desc: Setup Traefik
    dir: traefik
    cmds:
      - >
        helm upgrade --install traefik traefik/traefik
        --version 28.0.0
        --namespace traefik
        --create-namespace
        --values values.yaml
      - kubectl apply -f middlewares.yaml --namespace traefik

  setup-gitea:
    desc: Setup Gitea
    dir: gitea
    cmd: helmfile apply

  setup-vaultwarden:
    desc: Setup Vaultwarden
    dir: vaultwarden
    ignore_error: true
    cmds:
      - kubectl apply -f namespace.yaml
      - kubectl apply -f secrets.yaml
      - >
        helm upgrade --install postgres bitnami/postgresql
        --create-namespace
        --namespace vaultwarden
        --values pg-values.yaml
      - >
        helm upgrade --install vaultwarden vaultwarden/vaultwarden
        --create-namespace
        --namespace vaultwarden
        --values values.yaml

  setup-argocd:
    desc: Setup ArgoCD
    dir: argocd
    cmd: helmfile apply

  setup-monitoring:
    desc: Setup monitoring
    dir: promstack
    cmd: helmfile apply

  setup-zitadel:
    desc: Setup Zitadel
    dir: zitadel
    cmd: helmfile apply

  setup-core:
    desc: Setup core infra
    dir: core
    cmd: kubectl apply -f application.yaml

  setup-apps:
    desc: Setup prod apps
    dir: apps
    cmd: kubectl apply -f application.yaml

  tf-init:
    desc: Initialize Terraform
    dir: terraform/prod
    cmd: terraform init

  tf-plan:
    desc: Generate Terraform plan
    dir: terraform/prod
    cmd: terraform plan -out=.tfplan

  tf-apply:
    desc: Apply Terraform plan
    dir: terraform/prod
    cmd: terraform apply .tfplan
