version: 3

vars:
  SHORT_SHA:
    shell: git rev-parse --short HEAD

dotenv:
  - ./gitea/.env

tasks:
  setup-k8s:
    desc: Run first-time K8s & core infra setup
    dir: ansible
    cmds:
      - task: bootstrap-vms
      - task: setup-k8s-master
      - task: setup-k8s-workers
      - task: setup-traefik
      - task: setup-argocd

  bootstrap-vms:
    desc: Install pre-requisites in VMs
    internal: true
    dir: ansible
    cmds:
      - ansible-playbook -i inventory/hosts playbooks/setup-vm.yml

  setup-k8s-master:
    internal: true
    desc: Setup K8s master node
    dir: ansible
    cmds:
      - ansible-playbook -i inventory/hosts playbooks/setup-k8s-master.yml

  setup-k8s-workers:
    internal: true
    desc: Setup K8s worker nodes
    dir: ansible
    cmds:
      - ansible-playbook -i inventory/hosts playbooks/setup-k8s-workers.yml

  setup-init:
    desc: Initial setup
    cmds:
      - pre-commit install
      - helm repo add argo https://argoproj.github.io/argo-helm
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm repo add gitlab  https://charts.gitlab.io/
      - helm repo add traefik https://traefik.github.io/charts
      - helm repo add gitea https://dl.gitea.com/charts/
      - helm repo add nextcloud https://nextcloud.github.io/helm/
      - helm repo add hashicorp https://helm.releases.hashicorp.com
      - helm repo add firefly https://firefly-iii.github.io/kubernetes/
      - helm repo add drone https://charts.drone.io
      - helm repo add jameswynn https://jameswynn.github.io/helm-charts
      - helm repo add portainer https://portainer.github.io/k8s/
      - helm repo add secrets-store-csi-driver https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
      - helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
      - helm repo add minio-operator https://operator.min.io
      - helm repo update

  setup-traefik:
    desc: Setup Traefik
    dir: traefik
    cmds:
      - >
        helm upgrade --install traefik traefik/traefik
        --version 27.0.2
        --namespace traefik
        --create-namespace
        --values values.yaml
      - kubectl apply -f middlewares.yaml --namespace traefik

  setup-gitea:
    desc: Setup Gitea
    dir: gitea
    cmds:
      - kubectl apply -f namespace.yaml
      - kubectl apply -f configmap.yaml
      - >
        helm upgrade --install gitea gitea/gitea
        --version 10.1.4
        --namespace gitea
        --create-namespace
        --values values.yaml
        --set gitea.admin.username={{.GITEA_ADMIN_USERNAME}}
        --set gitea.admin.password={{.GITEA_ADMIN_PASSWORD}}
        --set gitea.admin.email={{.GITEA_ADMIN_EMAIL}}
        --set postgresql.auth.database={{.GITEA_POSTGRES_DATABASE}}
        --set postgresql.auth.password={{.GITEA_POSTGRES_PASSWORD}}
        --set postgresql.auth.username={{.GITEA_POSTGRES_USERNAME}}
      - kubectl apply -f ingress.yaml

  setup-vaultwarden:
    desc: Setup Vaultwarden
    dir: vaultwarden
    ignore_error: true
    cmds:
      - kubectl apply -f namespace.yaml
      - kubectl apply -f secrets.yaml
      - >
        helm upgrade --install postgres bitnami/postgresql
        --create-namespace
        --namespace vaultwarden
        --values pg-values.yaml
      - >
        helm upgrade --install vaultwarden vaultwarden/vaultwarden
        --create-namespace
        --namespace vaultwarden
        --values values.yaml

  setup-argocd:
    desc: Setup ArgoCD
    dir: argocd
    cmds:
      - kubectl apply -f namespace.yaml
      - kubectl apply -f secrets.yaml
      - kubectl apply -f cm.yaml
      - helm upgrade --install argocd argo/argo-cd --values values.yaml --namespace argocd

  setup-jellyfin:
    desc: Setup Jellyfin
    dir: arrstack
    cmds:
      - kubectl apply -f namespace.yaml
      - helm upgrade --install jellyfin ./jellyfin --namespace arrstack

  setup-calibre:
    desc: Setup Calibre
    dir: arrstack
    cmds:
      - kubectl apply -f namespace.yaml
      - helm upgrade --install calibre ./calibre --namespace arrstack

  setup-navidrome:
    desc: Setup Navidrome
    dir: arrstack
    cmds:
      - kubectl apply -f namespace.yaml
      - helm upgrade --install navidrome ./navidrome --namespace arrstack

  setup-arrstack:
    desc: Setup Arrstack
    dir: arrstack
    cmds:
      - kubectl apply -f namespace.yaml
      - helm upgrade --install flaresolverr ./flaresolverr --namespace arrstack
      - helm upgrade --install qbittorrent ./qbittorrent --namespace arrstack
      - helm upgrade --install prowlarr ./prowlarr --namespace arrstack
      - helm upgrade --install sonarr ./sonarr --namespace arrstack
      - helm upgrade --install radarr ./radarr --namespace arrstack
      - helm upgrade --install readarr ./readarr --namespace arrstack
      - helm upgrade --install lidarr ./lidarr --namespace arrstack
      - helm upgrade --install jellyseerr ./jellyseerr --namespace arrstack

  setup-core:
    desc: Setup core infra
    dir: core
    cmds:
      - kubectl apply -f application.yaml

  setup-apps:
    desc: Setup prod apps
    dir: apps
    cmds:
      - kubectl apply -f application.yaml
