apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: litellm-inf-secret
  labels: { }
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  syncConfig:
    resyncInterval: 10s
  authentication:
    kubernetesAuth:
      identityId: ea9c7e43-4921-4cac-bac7-8fc8b1a24440
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: infisical2
      secretsScope:
        projectSlug: litellm
        envSlug: prod
        secretsPath: /
        recursive: true
  managedKubeSecretReferences:
    - secretName: litellm-secrets
      secretNamespace: litellm
      creationPolicy: Owner
      template:
        includeAllSecrets: true
        metadata:
          annotations:
            helm.sh/hook: pre-install
            helm.sh/hook-weight: "-5"
            helm.sh/hook-delete-policy: before-hook-creation
  managedKubeConfigMapReferences:
    - configMapName: litellm-configmap
      configMapNamespace: litellm
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        metadata:
          annotations:
            helm.sh/hook: pre-install
            helm.sh/hook-weight: "-5"
            helm.sh/hook-delete-policy: before-hook-creation
        data:
          config.yaml: |-
            proxy_config:
              model_list:
                - model_name: gpt-6-astra
                  litellm_params:
                    model: gpt-6-astra
                    api_key: os.environ/OPENAI_API_KEY
                - model_name: gpt-5.6-sol
                  litellm_params:
                    model: gpt-5.6-sol
                    api_key: os.environ/OPENAI_API_KEY
                - model_name: gpt-5.6-terra
                  litellm_params:
                    model: gpt-5.6-terra
                    api_key: os.environ/OPENAI_API_KEY
                - model_name: gpt-5.6-luna
                  litellm_params:
                    model: gpt-5.6-luna
                    api_key: os.environ/OPENAI_API_KEY
                - model_name: claude-fable-5-1
                  litellm_params:
                    model: claude-fable-5-1
                    api_key: os.environ/ANTHROPIC_API_KEY
                - model_name: claude-opus-5
                  litellm_params:
                    model: claude-opus-5
                    api_key: os.environ/ANTHROPIC_API_KEY
                - model_name: claude-sonnet-5
                  litellm_params:
                    model: claude-sonnet-5
                    api_key: os.environ/ANTHROPIC_API_KEY
                - model_name: claude-haiku-4-5
                  litellm_params:
                    model: claude-haiku-4-5
                    api_key: os.environ/ANTHROPIC_API_KEY
                - model_name: gemini-3.8-flash
                  litellm_params:
                    model: gemini-3.8-flash
                    api_key: os.environ/GEMINI_API_KEY
                - model_name: gemini-3.5-flash-lite
                  litellm_params:
                    model: gemini-3.5-flash-lite
                    api_key: os.environ/GEMINI_API_KEY
                - model_name: gemini-3.1-pro-preview
                  litellm_params:
                    model: gemini-3.1-pro-preview
                    api_key: os.environ/GEMINI_API_KEY
              general_settings:
                master_key: os.environ/MASTER_KEY
