apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "metabase.fullname" . }}-secret'
  labels:
    {{- include "metabase.labels" . | nindent 4 }}
  annotations:
    avp.kubernetes.io/path: kv/data/lab/metabase
stringData:
  MB_DB_PASS: "<POSTGRESQL_PASSWORD>"
  MB_ENCRYPTION_SECRET_KEY: "<MB_ENCRYPTION_SECRET_KEY>"
