apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wallos.fullname" . }}-db
  labels:
    {{- include "wallos.labels" . | nindent 4 }}
  {{- with .Values.persistence.db.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.persistence.db.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.db.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wallos.fullname" . }}-logos
  labels:
    {{- include "wallos.labels" . | nindent 4 }}
  {{- with .Values.persistence.logos.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.persistence.logos.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.logos.size }}
