apiVersion: v1
kind: ConfigMap
metadata:
  name: hannibot-configmap
  labels:
    {{- include "hannibot.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
data:
  DJANGO_SETTINGS_MODULE: "kvisualbot.settings"
  POSTGRESQL_HOST: "{{- include "hannibot.fullname" . }}-postgresql"
  POSTGRESQL_PORT: "5432"
  POSTGRESQL_USERNAME: "postgres"
  POSTGRESQL_DATABASE: "hannibot"
  PORT: "5000"
  PRODUCTION: "true"
