apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{- include "hannibot.fullname" . }}-configmap'
  labels:
    {{- include "hannibot.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  BOT_PREFIX: "!"
  POSTGRESQL_HOST: 'hannibot-postgresql-hl'
  POSTGRESQL_PORT: "5432"
