apiVersion: batch/v1
kind: CronJob
metadata:
  name: '{{- include "hannibot.fullname" . }}-pull-comebacks'
  labels:
    {{- include "hannibot.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 10
  startingDeadlineSeconds: 300
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        {{- include "hannibot.labels" . | nindent 8 }}
    spec:
      template:
        metadata:
          labels:
            {{- include "hannibot.labels" . | nindent 12 }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: '{{ .Chart.Name }}-pull-comebacks'
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: '{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}'
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - python
                - -m
                - pipeline
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              {{- with .Values.volumeMounts }}
              volumeMounts:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              envFrom:
                - secretRef:
                    name: '{{- include "hannibot.fullname" . }}-secrets'
                - configMapRef:
                    name: '{{- include "hannibot.fullname" . }}-configmap'
  schedule: '0 0,6,12,18 * * *'
  timeZone: 'Asia/Seoul'
