apiVersion: v1
kind: Secret
metadata:
  name: hannibot-secrets
  labels:
    {{- include "hannibot.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    avp.kubernetes.io/path: kv/data/lab/hannibot
type: Opaque
stringData:
  POSTGRESQL_PASSWORD: "<POSTGRESQL_PASSWORD>"
  SECRET_KEY: "<SECRET_KEY>"
  DISCORD_ADMIN_ID: "<DISCORD_ADMIN_ID>"
  DISCORD_TEST_GUILD_ID: "<DISCORD_TEST_GUILD_ID>"
  DISCORD_TOKEN: "<DISCORD_TOKEN>"
