apiVersion: v1
kind: Secret
metadata:
  name: '{{- include "hannibot.fullname" . }}-secrets'
  labels:
    {{- include "hannibot.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
    avp.kubernetes.io/path: kv/data/lab/hannibot
type: Opaque
stringData:
  POSTGRESQL_PASSWORD: "<POSTGRESQL_PASSWORD>"
  DISCORD_ADMIN_ID: "<DISCORD_ADMIN_ID>"
  DISCORD_TEST_GUILD_ID: "<DISCORD_TEST_GUILD_ID>"
  DISCORD_TOKEN: "<DISCORD_TOKEN>"
  REDDIT_CLIENT_ID: "<REDDIT_CLIENT_ID>"
  REDDIT_CLIENT_SECRET: "<REDDIT_CLIENT_SECRET>"
