apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hannibot.fullname" . }}
  labels:
      {{- include "hannibot.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "hannibot.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /api/metrics
