apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: arrstack
  labels:
    app.kubernetes.io/name: prowlarr
    app.kubernetes.io/part-of: arrstack
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
