apiVersion: v1
kind: Secret
metadata:
  name: '{{- include "ihatemoney.fullname" . }}-secrets'
  labels:
    {{- include "ihatemoney.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    avp.kubernetes.io/path: kv/data/lab/ihatemoney
type: Opaque
stringData:
  SECRET_KEY: "<SECRET_KEY>"
  POSTGRESQL_PASSWORD: "<POSTGRESQL_PASSWORD>"
  SQLALCHEMY_DATABASE_URI: "<SQLALCHEMY_DATABASE_URI>"
  ADMIN_PASSWORD: "<ADMIN_PASSWORD>"
  ACTIVATE_ADMIN_DASHBOARD: "True"
