apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-kvd-studio-cert
spec:
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: dev-kvd-studio-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ""
  commonName: "*.dev.kvd.studio"
  dnsNames:
    - dev.kvd.studio
    - "*.dev.kvd.studio"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lab-kvd-studio-cert
spec:
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: lab-kvd-studio-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ""
  commonName: "*.lab.kvd.studio"
  dnsNames:
    - lab.kvd.studio
    - "*.lab.kvd.studio"
