apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
spec:
  defaultCertificate:
    secretName: lab-kvd-studio-tls
  certificates:
    - secretName: dev-kvd-studio-tls
    - secretName: banyuh-ai-tls
