acl local {
    10.0.0.0/8;
    127.0.0.0/8;
    172.16.0.0/12;
    192.168.0.0/16;
};

acl tailscale {
    100.64.0.0/10;
};

options {
    forwarders {
        1.1.1.1;
        1.0.0.1;
    };
    allow-query {
        local;
        tailscale;
    };
};

zone "dev.kvd.studio" IN {
    type master;
    file "/etc/bind/dev-kvd-studio.zone";
    allow-transfer {
        10.10.2.54;
    };
    also-notify {
        10.10.2.54;
    };
};

zone "lab.kvd.studio" IN {
    type master;
    file "/etc/bind/lab-kvd-studio.zone";
    allow-transfer {
        10.10.2.54;
    };
    also-notify {
        10.10.2.54;
    };
};

zone "pie.kvd.studio" IN {
    type master;
    file "/etc/bind/pie-kvd-studio.zone";
    allow-transfer {
        10.10.2.54;
    };
    also-notify {
        10.10.2.54;
    };
};

zone "swarm.kvd.studio" IN {
    type master;
    file "/etc/bind/swarm-kvd-studio.zone";
    allow-transfer {
        10.10.2.54;
    };
    also-notify {
        10.10.2.54;
    };
};
