apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{- include "discai.fullname" . }}-configmap'
  labels:
    {{- include "discai.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  DB_HOST: "10.10.10.103"
  DB_PORT: "5432"
  POSTGRESQL_USERNAME: "discai"
  POSTGRESQL_DATABASE: "discai"
  CHAT_MODEL: "claude-3-5-sonnet-latest"
