apiVersion: v1
kind: Secret
metadata:
  name: '{{- include "discai.fullname" . }}-secrets'
  labels:
    {{- include "discai.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
    avp.kubernetes.io/path: kv/data/lab/discai
type: Opaque
stringData:
  POSTGRESQL_PASSWORD: "<POSTGRESQL_PASSWORD>"
  ANTHROPIC_API_KEY: "<ANTHROPIC_API_KEY>"
  DISCORD_TOKEN: "<DISCORD_TOKEN>"
