apiVersion: v1
kind: ConfigMap
metadata:
  name: firefly-cm
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
data:
  DB_CONNECTION: "pgsql"
  DB_PORT: "5432"
  DB_DATABASE: "firefly"
  DB_USERNAME: "firefly"
  DB_HOST: "firefly-postgresql"
  DEFAULT_LANGUAGE: "en_US"
  DEFAULT_LOCALE: "equal"
  TZ: "Asia/Manila"
  TRUSTED_PROXIES: "**"
