apiVersion: v1
kind: ConfigMap
metadata:
  name: firefly-cm
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
data:
  DB_CONNECTION: "pgsql"
  DB_PORT: "5432"
  DB_DATABASE: "firefly"
  DB_USERNAME: "firefly"
  DB_HOST: "firefly-postgresql"
  DEFAULT_LANGUAGE: "en_US"
  DEFAULT_LOCALE: "equal"
  TZ: "Asia/Manila"
  TRUSTED_PROXIES: "**"
  MAIL_MAILER: "smtp"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_FROM: "hello@kvd.studio"
  MAIL_USERNAME: "hello@kvd.studio"
  MAIL_ENCRYPTION: "tls"
  ENABLE_EXTERNAL_RATES: "true"
  SITE_OWNER: "hello@kvd.studio"
  CACHE_DRIVER: "redis"
  SESSION_DRIVER: "redis"
  REDIS_HOST: "firefly-redis-master"
