apiVersion: v1
kind: Secret
metadata:
  name: firefly-secrets
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    avp.kubernetes.io/path: kv/data/lab/firefly
stringData:
  POSTGRES_PASSWORD: "<POSTGRES_PASSWORD>"
  REDIS_PASSWORD: "<REDIS_PASSWORD>"
  APP_KEY: "<APP_KEY>"
  STATIC_CRON_TOKEN: "<STATIC_CRON_TOKEN>"
  DB_PASSWORD: "<POSTGRES_PASSWORD>"
