{{- if .Values.config.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: firefly-configmap
  labels:
    {{- include "firefly-iii.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
data:
{{- range $key, $value := .Values.config.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
  APP_ENV: "local"
  APP_DEBUG: "false"
  SITE_OWNER: "hello@kvd.studio"
  DEFAULT_LANGUAGE: "en_US"
  TZ: "Asia/Manila"
  REDIS_HOST: "{{ .Release.Name }}-redis"
  MAIL_MAILER: "smtp"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_ENCRYPTION: "tls"
  ENABLE_EXTERNAL_RATES: "true"
{{- end }}
