  {{ if and (.Values.secrets.env) (not .Values.config.existingSecret) }}
  apiVersion: v1
  kind: Secret
  metadata:
    name: {{ include "firefly-iii.fullname" . }}
    labels:
    {{- include "firefly-iii.labels" . | nindent 4 }}
    annotations:
      helm.sh/hook: pre-install,pre-upgrade
      helm.sh/hook-weight: "-5"
      avp.kubernetes.io/path: "kv/data/lab/firefly"
  data:
    APP_KEY: "<APP_KEY>"
    STATIC_CRON_TOKEN: "<STATIC_CRON_TOKEN>"
    DB_PASSWORD: "<DB_PASSWORD>"
    POSTGRES_PASSWORD: "<POSTGRES_PASSWORD>"
    PGPASSWORD: "<PGPASSWORD>"
    DBPASSWORD: "<DBPASSWORD>"
    REDIS_PASSWORD: "<REDIS_PASSWORD>"
    MAIL_FROM: "<MAIL_FROM>"
    MAIL_USERNAME: "<MAIL_USERNAME>"
    MAIL_PASSWORD: "<MAIL_PASSWORD>"
{{- end }}
