services:
  act:
    image: gitea/act_runner:0.2.6
    restart: unless-stopped
    user: "0:0"
    env_file: .env
    environment:
      TZ: Asia/Manila
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
