services:
  act:
    image: vegardit/gitea-act-runner:dind-rootless-0.2.6
    restart: unless-stopped
    privileged: true
    env_file: .env
    environment:
      TZ: Asia/Manila
    volumes:
      - data:/data

volumes:
  data:
