apiVersion: v1
kind: Secret
metadata:
  name: maybe-secrets
  labels:
    app.kubernetes.io/part-of: traefik
  annotations:
    avp.kubernetes.io/path: kv/data/lab/maybe
type: Opaque
stringData:
  POSTGRESQL_PASSWORD: "<POSTGRESQL_PASSWORD>"
  SECRET_KEY_BASE: "<SECRET_KEY_BASE>"
  SYNTH_API_KEY: "<SYNTH_API_KEY>"
