- name: Increase inotify values
  loop:
    - fs.inotify.max_user_instances
    - fs.inotify.max_user_watches
    - fs.inotify.max_queued_events
  ansible.posix.sysctl:
    name: '{{ item }}'
    value: 524288
    state: present

- name: Ensure Downloads directory exists
  ansible.builtin.file:
    path: ~/Downloads
    state: directory
    mode: '755'

- name: Setup K3s
  block:
    - name: Download K3s installer
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: ~/Downloads/install-k3s.sh
        mode: '755'

    - name: Install K3s
      environment:
        INSTALL_K3S_CHANNEL: '{{ k8s_version }}'
      ansible.builtin.shell: >
        ~/Downloads/install-k3s.sh server
        --cluster-init
        --write-kubeconfig-mode 644
        --disable=traefik,coredns,metrics-server
        --docker
      changed_when: false

- name: Get kubeconfig
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ./outputs/rpi5-kubeconfig.yaml
    flat: true

- name: Get node token
  ansible.builtin.fetch:
    src: /var/lib/rancher/k3s/server/node-token
    dest: ./outputs/rpi5-node-token
    flat: true
