apiVersion: v1
kind: Secret
metadata:
  name: time-machine-secrets
  labels:
    {{- include "time-machine.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
    avp.kubernetes.io/path: kv/data/lab/time-machine
type: Opaque
stringData:
  POSTGRESQL_PASSWORD: "<POSTGRESQL_PASSWORD>"
