apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: plane-inf-secret
  labels: { }
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  syncConfig:
    resyncInterval: 10s
  authentication:
    kubernetesAuth:
      identityId: ea9c7e43-4921-4cac-bac7-8fc8b1a24440
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: infisical2
      secretsScope:
        projectSlug: plane
        envSlug: prod
        secretsPath: /
        recursive: true
  managedKubeSecretReferences:
    - secretName: plane-secrets
      secretNamespace: plane
      creationPolicy: Owner
      template:
        includeAllSecrets: true
        metadata:
          annotations:
            helm.sh/hook: pre-install
            helm.sh/hook-weight: "-5"
            helm.sh/hook-delete-policy: before-hook-creation
        data:
          AMQP_URL: "amqp://plane:{{ .AMQP_PASSWORD.Value }}@plane-rabbitmq"
          DATABASE_URL: "postgres://plane:{{ .POSTGRESQL_PASSWORD.Value }}@10.10.10.103:5432/plane"
          POSTGRES_DB: "plane"
          POSTGRES_PASSWORD: "{{ .POSTGRESQL_PASSWORD.Value }}"
          POSTGRES_USER: "plane"
          REDIS_URL: "redis://plane-redis:6379"
          AWS_REGION: "ap-southeast-1"
          AWS_S3_BUCKET_NAME: "plane"
          AWS_S3_ENDPOINT_URL: "https://api-minio.lab.kvd.studio"
          FILE_SIZE_LIMIT: "10485760"
          USE_MINIO: "0"
          RABBITMQ_DEFAULT_USER: "plane"
