apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ include "lubelogger.fullname" . }}-data'
  labels:
    {{ include "lubelogger.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ include "lubelogger.fullname" . }}-keys'
  labels:
    {{ include "lubelogger.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
