apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: time-machine
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://git.lab.kvd.studio/r/homelab.git
      targetRevision: main
      path: time-machine/time-machine
      plugin:
        name: argocd-vault-plugin-helm
  destination:
    server: https://kubernetes.default.svc
    namespace: time-machine
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
