x-common-http-router: &common-http-router
  entryPoints:
    - https
  middlewares:
    - secured
  tls: {}

http:
  routers:
    homepage:
      rule: "Host(`homepage.dev.kvd.studio`)"
      service: homepage
      <<: *common-http-router
    pterodactyl:
      rule: "Host(`pterodactyl.dev.kvd.studio`)"
      service: pterodactyl
      <<: *common-http-router
    uptime-kuma:
      rule: "Host(`uptime.dev.kvd.studio`)"
      service: uptime-kuma
      <<: *common-http-router
    pfsense:
      rule: "Host(`pfsense.dev.kvd.studio`)"
      service: pfsense
      <<: *common-http-router
    bastion:
      rule: "Host(`bastion.dev.kvd.studio`)"
      service: bastion
      <<: *common-http-router
    aurora:
      rule: "Host(`aurora.dev.kvd.studio`)"
      service: aurora
      <<: *common-http-router
    truenas:
      rule: "Host(`truenas.dev.kvd.studio`)"
      service: truenas
      <<: *common-http-router
    jellyfin:
      rule: "Host(`jellyfin.dev.kvd.studio`)"
      service: jellyfin
      <<: *common-http-router
    pihole1:
      rule: "Host(`pihole1.dev.kvd.studio`)"
      service: pihole1
      <<: *common-http-router
    pihole2:
      rule: "Host(`pihole2.dev.kvd.studio`)"
      service: pihole2
      <<: *common-http-router
    wings:
      rule: "Host(`wings0.dev.kvd.studio`)"
      service: wings
      <<: *common-http-router
    prowlarr:
      rule: "Host(`prowlarr.dev.kvd.studio`)"
      service: prowlarr
      <<: *common-http-router
    flaresolverr:
      rule: "Host(`flaresolverr.dev.kvd.studio`)"
      service: flaresolverr
      <<: *common-http-router
    sonarr:
      rule: "Host(`sonarr.dev.kvd.studio`)"
      service: sonarr
      <<: *common-http-router
    jellyseerr:
      rule: "Host(`jellyseerr.dev.kvd.studio`)"
      service: jellyseerr
      <<: *common-http-router
    radarr:
      rule: "Host(`radarr.dev.kvd.studio`)"
      service: radarr
      <<: *common-http-router
    lidarr:
      rule: "Host(`lidarr.dev.kvd.studio`)"
      service: lidarr
      <<: *common-http-router
    qbittorrent:
      rule: "Host(`qbittorrent.dev.kvd.studio`)"
      service: qbittorrent
      <<: *common-http-router
    readarr:
      rule: "Host(`readarr.dev.kvd.studio`)"
      service: readarr
      <<: *common-http-router
    portainer:
      rule: "Host(`portainer.dev.kvd.studio`)"
      service: portainer
      <<: *common-http-router
    dblab-api:
      rule: "Host(`dblab-api.dev.kvd.studio`)"
      service: dblab-api
      <<: *common-http-router
    dblab:
      rule: "Host(`dblab.dev.kvd.studio`)"
      service: dblab
      <<: *common-http-router

  services:
    homepage:
      loadBalancer:
        servers:
          - url: "http://10.10.10.101:3000"
        passHostHeader: true
    pterodactyl:
      loadBalancer:
        servers:
          - url: "http://10.10.10.101:8080"
        passHostHeader: true
    uptime-kuma:
      loadBalancer:
        servers:
          - url: "http://10.10.10.101:3001"
        passHostHeader: true
    pfsense:
      loadBalancer:
        servers:
          - url: "http://10.10.0.1"
        passHostHeader: true
    bastion:
      loadBalancer:
        servers:
          - url: "https://10.10.0.200:8006"
        passHostHeader: true
    aurora:
      loadBalancer:
        servers:
          - url: "https://10.10.10.99:8006"
        passHostHeader: true
    truenas:
      loadBalancer:
        servers:
          - url: "http://10.10.10.100"
        passHostHeader: true
    jellyfin:
      loadBalancer:
        servers:
          - url: "http://10.10.10.100:8096"
        passHostHeader: true
    pihole1:
      loadBalancer:
        servers:
          - url: "http://10.10.1.53"
        passHostHeader: true
    pihole2:
      loadBalancer:
        servers:
          - url: "http://10.10.2.53"
        passHostHeader: true
    wings:
      loadBalancer:
        servers:
          - url: "http://10.10.10.104:443"
        passHostHeader: true
    prowlarr:
      loadBalancer:
        servers:
          - url: "http://10.10.10.100:9696"
        passHostHeader: true
    flaresolverr:
      loadBalancer:
        servers:
          - url: "http://10.10.10.100:8191"
        passHostHeader: true
    sonarr:
      loadBalancer:
        servers:
          - url: "http://10.10.10.100:8989"
        passHostHeader: true
    jellyseerr:
      loadBalancer:
        servers:
          - url: "http://10.10.10.100:10241"
        passHostHeader: true
    radarr:
      loadBalancer:
        servers:
          - url: "http://10.10.10.100:7878"
        passHostHeader: true
    lidarr:
      loadBalancer:
        servers:
          - url: "http://10.10.10.100:8686"
        passHostHeader: true
    qbittorrent:
      loadBalancer:
        servers:
          - url: "http://10.10.10.100:10095"
        passHostHeader: true
    readarr:
      loadBalancer:
        servers:
          - url: "http://10.10.10.100:30045"
        passHostHeader: true
    portainer:
      loadBalancer:
        servers:
          - url: "http://10.10.10.100:31017"
        passHostHeader: true
    dblab-api:
      loadBalancer:
        servers:
          - url: "http://10.10.10.103:2345"
        passHostHeader: true
    dblab:
      loadBalancer:
        servers:
          - url: "http://10.10.10.103:2346"
        passHostHeader: true

  middlewares:
    default-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        frameDeny: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
    default-whitelist:
      ipAllowList:
        sourceRange:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 100.64.0.0/10
          - 192.168.0.0/16
          - 127.0.0.0/8
    secured:
      chain:
        middlewares:
          - default-headers
          - default-whitelist

tcp:
  services:
    wings:
      loadBalancer:
        servers:
          - address: "10.10.10.104:2022"
    pg:
      loadBalancer:
        servers:
          - address: "10.10.10.103:5432"
    pgpool:
      loadBalancer:
        servers:
          - address: "10.10.10.103:6543"

  routers:
    wings:
      entryPoints:
        - sftp
      rule: "HostSNI(`wings0.dev.kvd.studio`)"
      service: wings
      tls:
        passthrough: true
    pg:
      rule: "HostSNI(`pg.lab.kvd.studio`)"
      service: pg
      entryPoints:
        - pg
      tls:
        options: postgres
    pgpool:
      rule: "HostSNI(`pg.lab.kvd.studio`)"
      service: pgpool
      entryPoints:
        - pgpool
      tls:
        options: postgres

tls:
  options:
    postgres:
      alpnProtocols:
        - postgresql
