networks:
  traefik:
    name: traefik
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
    driver_opts:
      com.docker.network.bridge.name: traefik

volumes:
  acme-data:

services:
  traefik:
    image: traefik:v3
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
      CF_ZONE_API_TOKEN: ${CF_ZONE_API_TOKEN}
    ports:
      - 80:80
      - 443:443
      - 5432:5432
      - 6543:6543
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./config.yml:/config.yml:ro
      - acme-data:/etc/traefik/acme
    networks:
      - default
      - traefik
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.entrypoints: https
      traefik.http.routers.traefik.rule: Host(`traefik.dev.kvd.studio`)
      traefik.http.routers.traefik.tls: true
      traefik.http.routers.traefik.tls.certresolver: cloudflare
      traefik.http.routers.traefik.tls.domains[0].main: dev.kvd.studio
      traefik.http.routers.traefik.tls.domains[0].sans: "*.dev.kvd.studio"
      traefik.http.routers.traefik.tls.domains[1].main: lab.kvd.studio
      traefik.http.routers.traefik.tls.domains[1].sans: "*.lab.kvd.studio"
      traefik.http.routers.traefik.service: api@internal
      traefik.http.services.traefik.loadbalancer.server.port: 8080
      traefik.http.routers.traefik.middlewares: secured@file

  master:
    image: ubuntu/bind9:9.20-24.10_beta
    environment:
      BIND9_USER: root
      TZ: Asia/Manila
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
    restart: unless-stopped
