apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{- include "supertokens.fullname" . }}-configmap'
  labels:
    {{- include "supertokens.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
data:
  SUPERTOKENS_HOST: "supertokens.lab.kvd.studio"
  SUPERTOKENS_PORT: "{{ .Values.service.port }}"
  POSTGRESQL_USER: "{{ .Values.postgresql.auth.username }}"
  POSTGRESQL_DATABASE_NAME: "{{ .Values.postgresql.auth.database }}"
  POSTGRESQL_HOST: "{{ .Release.Name }}-postgresql-hl"
  POSTGRESQL_PORT: "5432"
