apiVersion: v1
kind: Secret
metadata:
  name: '{{- include "supertokens.fullname" . }}-secrets'
  labels:
    {{- include "supertokens.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    avp.kubernetes.io/path: kv/data/lab/supertokens
stringData:
  POSTGRESQL_PASSWORD: "<POSTGRESQL_PASSWORD>"
