apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: droneci
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.drone.io
    targetRevision: 0.6.5
    chart: drone
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            ingress:
              enabled: true
              annotations:
                gethomepage.dev/enabled: "true"
                gethomepage.dev/name: "Drone CI"
                gethomepage.dev/group: "CI/CD"
                gethomepage.dev/icon: "drone.png"
                gethomepage.dev/ping: "drone.lab.kvd.studio"
              hosts:
                - host: drone.lab.kvd.studio
                  paths:
                    - path: /
                      pathType: Prefix
            env:
              DRONE_SERVER_HOST: drone.lab.kvd.studio
              DRONE_SERVER_PROTO: https
              DRONE_GITEA_CLIENT_ID: <path:kv/data/lab/droneci#DRONE_GITEA_CLIENT_ID>
              DRONE_GITEA_CLIENT_SECRET: <path:kv/data/lab/droneci#DRONE_GITEA_CLIENT_SECRET>
              DRONE_GITEA_SERVER: https://git.lab.kvd.studio
              DRONE_GIT_ALWAYS_AUTH: true
              DRONE_RPC_SECRET: <path:kv/data/lab/droneci#DRONE_RPC_SECRET>
  destination:
    server: https://kubernetes.default.svc
    namespace: droneci
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
