apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: secure-headers
  labels:
    app.kubernetes.io/name: traefik
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    frameDeny: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 15552000
    customFrameOptionsValue: SAMEORIGIN
    customRequestHeaders:
      X-Forwarded-Proto: https
      X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ip-whitelist
  labels:
    app.kubernetes.io/name: traefik
spec:
  ipWhiteList:
    sourceRange:
      - 127.0.0.1/32 # loopback
      - 10.0.0.0/8 # LAN, K8s internal cluster
      - 172.16.0.0/12 # Docker internal bridge
      - 100.64.0.0/10 # Tailscale
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: compress
  labels:
    app.kubernetes.io/name: traefik
spec:
  compress: {}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: retry
  labels:
    app.kubernetes.io/name: traefik
spec:
  retry:
    attempts: 3
    initialInterval: 5s
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: secured
  labels:
    app.kubernetes.io/name: traefik
spec:
  chain:
    middlewares:
      - name: secure-headers
      - name: ip-whitelist
