apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik
  labels:
    storage.k8s.io/name: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 32Mi
