apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ include "solidtime.fullname" . }}-app-storage'
  labels:
    {{ include "solidtime.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
