apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-app-ini-configmap
  labels:
    app: gitea
  namespace: gitea
data:
  server: |
    SSH_PORT=3322
    DOMAIN=git.lab.kvd.studio
    SSH_DOMAIN=git.lab.kvd.studio
    ROOT_URL=https://git.lab.kvd.studio
    LFS_START_SERVER=true
  repository: |
    DEFAULT_REPO_UNITS=repo.code, repo.releases, repo.issues, repo.pulls, repo.wiki, repo.projects, repo.packages, repo.actions
    DEFAULT_BRANCH=main
  repository.pull-request: |
    DEFAULT_MERGE_STYLE=squash
    POPULATE_SQUASH_COMMENT_WITH_COMMIT_MESSAGES=true
  webhook: |
    ALLOWED_HOST_LIST=loopback,private,*.dev.kvd.studio,*.lab.kvd.studio
  markup: |
    ENABLED=true
  actions: |
    ENABLED=true
  security: |
    LOGIN_REMEMBER_DAYS=14
  database: |
    HOST=gitea-postgresql-hl
  service: |
    DISABLE_REGISTRATION=true
