apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: superset-inf-secret
  labels: { }
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  syncConfig:
    resyncInterval: 10s
  authentication:
    kubernetesAuth:
      identityId: ea9c7e43-4921-4cac-bac7-8fc8b1a24440
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: infisical2
      secretsScope:
        projectSlug: superset
        envSlug: prod
        secretsPath: /
        recursive: true
  managedKubeSecretReferences:
    - secretName: superset-secrets
      secretNamespace: superset
      creationPolicy: Owner
      template:
        includeAllSecrets: true
        metadata:
          annotations:
            helm.sh/hook: pre-install
            helm.sh/hook-weight: "-5"
            helm.sh/hook-delete-policy: before-hook-creation
        data:
          DB_PASS: "{{ .POSTGRESQL_PASSWORD.Value }}"
          password: "{{ .POSTGRESQL_PASSWORD.Value }}"
          postgres-password: "{{ .POSTGRESQL_PASSWORD.Value }}"
