apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kvdomingo/homelab-automation.git
    targetRevision: main
    path: core/apps
    helm:
      releaseName: core-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
