apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-core
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://git.lab.kvd.studio/r/homelab.git
    targetRevision: main
    path: core/apps
    helm:
      releaseName: prod-core
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
