image:
  repository: ghcr.io/gethomepage/homepage
  tag: v0.8.0

# Enable RBAC. RBAC is necessary to use Kubernetes integration
enableRbac: true

serviceAccount:
  # Specify a different service account name
  name: homepage
  # Create service account. Needed when RBAC is enabled.
  create: true

service:
  main:
    ports:
      http:
        port: 3000

controller:
  strategy: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

# Enable the ingress to expose Homepage to the network.
ingress:
  main:
    enabled: true
    annotations:
      # These annotations will configure how this deployment is shown in Homepage
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Homepage"
      gethomepage.dev/description: "A modern, secure, highly customizable application dashboard."
      gethomepage.dev/group: "Admin"
      gethomepage.dev/icon: "homepage.png"
      gethomepage.dev/ping: "home.lab.kvd.studio"
    ingressClassName: traefik
    hosts:
      - host: home.lab.kvd.studio
        paths:
          - path: /
            pathType: Prefix
    # tls:
    #   - hosts:
    #       - *host

x-three-columns: &three-columns
  style: row
  columns: 3

# All the config files for Homepage can be specified under their relevant config block.
config:
  # To use an existing ConfigMap uncomment this line and specify the name
  # useExistingConfigMap: existing-homepage-configmap
  bookmarks:
  #    - Developer:
  #        - Github:
  #            - abbr: GH
  #              href: https://github.com/
  services:
    - Networking:
        - Cloudflare:
            icon: cloudflare.png
            widget:
              type: cloudflared
              accountid: ""
              tunnelid: ""
              key: ""
  widgets:
    - logo:
        icon: https://res.cloudinary.com/kdphotography-assets/image/upload/v1597254769/logo/logo-white.png
    - resources:
        # change backend to 'kubernetes' to use Kubernetes integration. Requires RBAC.
        backend: kubernetes
        expanded: true
        cpu: true
        memory: true
        disk: /
    - search:
        provider: google
        target: _blank
    - datetime:
        text_size: xl
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
    - openmeteo:
        label: Plaridel
        units: metric
        cache: 5
        timezone: Asia/Manila
        latitude: 14.88
        longitude: 120.85
    ## Uncomment to enable Kubernetes integration
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
  kubernetes:
    # change mode to 'cluster' to use RBAC service account
    mode: cluster
  docker:
  settings:
    layout:
      Admin:
        <<: *three-columns
      Media:
        <<: *three-columns
      Networking:
        <<: *three-columns
      CI/CD:
        <<: *three-columns
    headerStyle: underlined
    quickLaunch:
      searchDescriptions: true
      hideInternetSearch: false
      hideVisitURL: false
    showStats: false
    background: https://apod.local.kvdomingo.dev
    backgroundOpacity: 0.33

persistence:
  logs:
    enabled: false
    type: emptyDir
    mountPath: /app/config/logs

# resources:
#   requests:
#     memory: 10Mi
#     cpu: 10m
#   limits:
#     memory: 200Mi
#     cpu: 500m
