#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/a081de5/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: vabene1111/recipes
  # -- image tag
  tag: 1.5.10
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag

# -- environment variables. [[ref]](https://github.com/TandoorRecipes/recipes/blob/master/.env.template).
# @default -- See [values.yaml](./values.yaml)
env:
  # -- default timezone
  TIMEZONE: Asia/Manila

service:
  # -- Configures service settings for the chart.
  # @default -- See [values.yaml](./values.yaml)
  main:
    ports:
      http:
        port: 8080
      static:
        port: 80

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: true
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Tandoor"
      gethomepage.dev/group: "Documents"
      gethomepage.dev/icon: "tandoor.png"
      gethomepage.dev/ping: "tandoor.lab.kvd.studio"
    hosts:
      - host: tandoor.lab.kvd.studio
        paths:
          - path: /
          - path: /static
            service:
              port: 80
          - path: /media
            service:
              port: 80

# -- Configure persistence settings for the chart under this key.
# @default -- See [values.yaml](./values.yaml)
persistence:
  config:
    enabled: true
    retain: true
    # storageClass: ""
    accessMode: ReadWriteOnce
    size: 1Gi
  media:
    enabled: true
    mountPath: /opt/recipes/mediafiles
    retain: true
    # storageClass: ""
    accessMode: ReadWriteOnce
    size: 1Gi
  static:
    enabled: true
    type: emptyDir
    mountPath: /opt/recipes/staticfiles
  django-js-reverse:
    enabled: true
    type: emptyDir
    mountPath: /opt/recipes/cookbook/static/django_js_reverse

# -- Enable and configure postgresql database subchart under this key. [[ref]](https://github.com/bitnami/charts/tree/master/bitnami/mariadb)
# @default -- See [values.yaml](./values.yaml)
postgresql:
  enabled: true
  auth:
    username: tandoor
    database: tandoor
    existingSecret: tandoor-secrets
    secretKeys:
      adminPasswordKey: POSTGRESQL_PASSWORD
      userPasswordKey: POSTGRESQL_PASSWORD
      replicationPasswordKey: POSTGRESQL_PASSWORD
  primary:
    persistence:
      enabled: true
      size: 8Gi
    livenessProbe:
      enabled: true
      initialDelaySeconds: 300
      timeoutSeconds: 15
      periodSeconds: 20
      successThreshold: 1
      failureThreshold: 3
  volumePermissions:
    enabled: true
  serviceAccount:
    create: true
  rbac:
    create: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

podSecurityContext:
  # -- Run as `nobody` user
  runAsUser: 65534
  # -- Run as `nobody` group
  runAsGroup: 65534
  # -- Volume binds will be granted to `nobody` group
  fsGroup: 65534
