root = "."
tmp_dir = ".tmp"

[build]
cmd = "go build -o ./application ."
bin = "application"
full_bin = "./application"
include_ext = ["go", "tpl", "tmpl", "html", "mustache", "hbs", "pug"]
exclude_dir = ["tmp", "vendor", "node_modules"]
include_dir = []
exclude_file = []
log = "air.log"
delay = 1000
stop_on_error = true
send_interrupt = false
kill_delay = 500

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
