apiVersion: v1
kind: Secret
metadata:
  name: '{{- include "cloudflare.fullname" . }}-secrets'
  labels:
    {{- include "cloudflare.labels" . | nindent 4 }}
  annotations:
    avp.kubernetes.io/path: kv/data/lab/cloudflare
type: Opaque
stringData:
  CLOUDFLARE_TUNNEL_TOKEN: "<CLOUDFLARE_TUNNEL_TOKEN>"
  CLOUDFLARE_TUNNEL_ID: "<CLOUDFLARE_TUNNEL_ID>"
  CLOUDFLARE_TUNNEL_NAME: "<CLOUDFLARE_TUNNEL_NAME>"
  CLOUDFLARE_ACCOUNT_NUMBER: "<CLOUDFLARE_ACCOUNT_NUMBER>"
