apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: arrstack
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/part-of: arrstack
  annotations:
    helm.sh/resource-policy: keep
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
