apiVersion: v1
kind: ConfigMap
metadata:
  name: go-tracker-configmap
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
data:
  REDIS_PORT: "6379"
  REDIS_HOST: "go-tracker-redis-master"
  REDIS_OM_URL: "redis://go-tracker-redis:6379"
  MAIL_SERVER: "smtp.gmail.com"
  MAIL_PORT: "587"
