apiVersion: v1
kind: Secret
metadata:
  name: go-tracker-secrets
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    avp.kubernetes.io/path: kv/data/lab/go-tracker
stringData:
  REDIS_PASSWORD: "<REDIS_PASSWORD>"
  MAIL_USERNAME: "<MAIL_USERNAME>"
  MAIL_PASSWORD: "<MAIL_PASSWORD>"
  MAIL_RECIPIENT: "<MAIL_RECIPIENT>"
