apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "go-tracker.fullname" . }}
  labels:
      {{- include "go-tracker.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "go-tracker.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
