apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: arrstack
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: arrstack
  annotations:
    helm.sh/resource-policy: keep
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-series
  namespace: arrstack
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: arrstack
  annotations:
    helm.sh/resource-policy: keep
spec:
  resources:
    requests:
      storage: 512Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-movies
  namespace: arrstack
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: arrstack
  annotations:
    helm.sh/resource-policy: keep
spec:
  resources:
    requests:
      storage: 512Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
