postgresql:
  auth:
    existingSecret: firefly-secrets
    username: firefly
    database: firefly
    secretKeys:
      adminPasswordKey: POSTGRES_PASSWORD
      replicationPasswordKey: POSTGRES_PASSWORD
      userPasswordKey: POSTGRES_PASSWORD
  volumePermissions:
    enabled: true

redis:
  auth:
    enabled: true
    existingSecret: firefly-secrets
    existingSecretPasswordKey: REDIS_PASSWORD
  architecture: standalone
  volumePermissions:
    enabled: true

firefly-iii:
  # -- Set to false to not deploy Firefly III
  enabled: true
  config:
    existingSecret: firefly-secrets
    existingConfigMap: firefly-cm
  ingress:
    enabled: true
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Firefly"
      gethomepage.dev/group: "Finances"
      gethomepage.dev/icon: "firefly.png"
      gethomepage.dev/ping: "firefly.lab.kvd.studio"
    hosts:
      - firefly.lab.kvd.studio

importer:
  # -- Set to false to not deploy the importer
  enabled: true
  config:
    existingSecret: firefly-secrets
