apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{- include "docmost.fullname" . }}-configmap'
  labels:
    {{- include "docmost.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  APP_URL: "https://{{ (index .Values.ingress.hosts 0).host }}"
