apiVersion: v1
kind: Secret
metadata:
  name: '{{- include "docmost.fullname" . }}-secrets'
  labels:
    {{- include "docmost.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
    avp.kubernetes.io/path: kv/data/lab/docmost
stringData:
  APP_SECRET: "<APP_SECRET>"
  POSTGRESQL_PASSWORD: "<POSTGRESQL_PASSWORD>"
  DATABASE_URL: "postgresql://{{ .Values.postgresql.auth.username }}:<path:kv/data/lab/docmost#POSTGRESQL_PASSWORD>@{{ .Release.Name }}-postgresql-hl:5432/{{ .Values.postgresql.auth.database }}?schema=public"
  REDIS_URL: "redis://{{ .Release.Name }}-redis-headless:6379"
