apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{- include "librechat.fullname" . }}-configmap'
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  HOST: "0.0.0.0"
  PORT: "{{ .Values.service.port }}"
  STATIC_CACHE_MAX_AGE: "172800"
  STATIC_CACHE_S_MAX_AGE: "86400"
  DISABLE_COMPRESSION: "false"
  DOMAIN_CLIENT: "https://{{ (index .Values.ingress.hosts 0).host }}"
  DOMAIN_SERVER: "https://{{ (index .Values.ingress.hosts 0).host }}"
  NO_INDEX: "true"
  ENDPOINTS: "openAI,assistants,gptPlugins,azureOpenAI,google,anthropic,bingAI,custom"
  TITLE_CONVO: "true"
  ANTHROPIC_MODELS: "claude-3-5-opus-latest,claude-3-5-sonnet-latest,claude-3-5-haiku-latest"
  ANTHROPIC_TITLE_MODEL: "claude-3-5-sonnet-latest"
  OPENAI_MODELS: "gpt-4o-2024-08-06,gpt-4o-realtime-preview-2024-10-01,gpt-4-turbo-2024-04-09,gpt-4o-mini-2024-07-18,dall-e-3"
  OPENAI_TITLE_MODEL: "gpt-4o-mini-2024-07-18"
  OPENAI_SUMMARIZE: "true"
  OPENAI_SUMMARY_MODEL: "gpt-4o-mini-2024-07-18"
  OPENAI_MODERATION: "false"
  LIMIT_CONCURRENT_MESSAGES: "true"
  CONCURRENT_MESSAGE_MAX: "2"
  ALLOW_EMAIL_LOGIN: "true"
  ALLOW_REGISTRATION: "true"
  ALLOW_SOCIAL_LOGIN: "true"
  ALLOW_SOCIAL_REGISTRATION: "true"
  ALLOW_PASSWORD_RESET: "true"
  ALLOW_ACCOUNT_DELETION: "true"
  ALLOW_UNVERIFIED_EMAIL_LOGIN: "false"
  SESSION_EXPIRY: "604800000"
  REFRESH_TOKEN_EXPIRY: "1209600000"
  GITHUB_CALLBACK_URL: "/oauth/github/callback"
  GOOGLE_CALLBACK_URL: "/oauth/google/callback"
  SHOW_BIRTHDAY_ICON: "true"
