apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{- include "librechat.fullname" . }}-configmap'
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  HOST: "0.0.0.0"
  PORT: "{{ .Values.service.port }}"
  CONFIG_PATH: "/config/librechat.yaml"
  DOMAIN_CLIENT: "https://{{ (index .Values.ingress.hosts 0).host }}"
  DOMAIN_SERVER: "https://{{ (index .Values.ingress.hosts 0).host }}"
  NO_INDEX: "true"
  CONSOLE_JSON: "false"
  DEBUG_LOGGING: "false"
  DEBUG_CONSOLE: "false"
  RAG_API_URL: 'http://{{- include "librechat.fullname" . }}-rag-api'
  RAG_PORT: "{{ .Values.rag.service.port }}"
  MEILI_HOST: '{{ include "librechat.fullname" . }}-meilisearch'
  ENDPOINTS: "openAI,assistants,agents,gptPlugins,google,anthropic,xai,custom"
  ANTHROPIC_MODELS: "claude-3-7-sonnet-latest,claude-3-5-sonnet-latest,claude-3-5-haiku-latest,claude-3-opus-latest"
  ANTHROPIC_TITLE_MODEL: "claude-3-5-haiku-latest"
  OPENAI_MODELS: "o4-mini,o3-mini,o1-mini,o3,o1,gpt-4.1,gpt-4o,gpt-4o-nano,gpt-4o-mini,gpt-4.1-mini,gpt-4o-realtime"
  OPENAI_TITLE_MODEL: "gpt-4o-nano"
  GOOGLE_MODELS: "gemini-2.5-pro-preview-03-25,gemini-2.0-flash,gemini-2.0-flash-lite,gemini-1.5-flash,gemini-1.5-pro"
  GOOGLE_TITLE_MODEL: "gemini-2.0-flash-lite"
  DEBUG_OPENAI: "false"
  TITLE_CONVO: "true"
  OPENAI_SUMMARIZE: "true"
  OPENAI_SUMMARY_MODEL: "gpt-4o-mini"
  DEBUG_PLUGINS: "false"
  SEARCH: "true"
  ALLOW_EMAIL_LOGIN: "true"
  ALLOW_REGISTRATION: "false"
  ALLOW_SOCIAL_LOGIN: "true"
  ALLOW_SOCIAL_REGISTRATION: "true"
  ALLOW_PASSWORD_RESET: "true"
  ALLOW_ACCOUNT_DELETION: "true"
  ALLOW_UNVERIFIED_EMAIL_LOGIN: "true"
  SESSION_EXPIRY: "1000 * 60 * 15"
  REFRESH_TOKEN_EXPIRY: "1000 * 60 * 60 * 24 * 7"
  STATIC_CACHE_MAX_AGE: "172800"
  STATIC_CACHE_S_MAX_AGE: "86400"
  DISABLE_COMPRESSION: "false"
  LIMIT_CONCURRENT_MESSAGES: "true"
  CONCURRENT_MESSAGE_MAX: "2"
  GITHUB_CALLBACK_URL: "/oauth/github/callback"
  GOOGLE_CALLBACK_URL: "/oauth/google/callback"
  SHOW_BIRTHDAY_ICON: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{- include "librechat.fullname" . }}-rag-api-configmap'
  labels:
    {{- include "librechatRag.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  DB_HOST: "srv-pg-01.lab"
  DB_PORT: "5432"
  POSTGRES_USER: "librechat"
  POSTGRES_DB: "librechat"
  RAG_PORT: "{{ .Values.rag.service.port }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{- include "librechat.fullname" . }}-meilisearch-configmap'
  labels:
    {{- include "librechatMeilisearch.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  MEILI_HOST: '{{ include "librechat.fullname" . }}-meilisearch'
  MEILI_NO_ANALYTICS: "true"
