apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{- include "librechat.fullname" . }}-configmap'
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  HOST: "0.0.0.0"
  PORT: "{{ .Values.service.port }}"
  CONFIG_PATH: "/config/librechat.yaml"
  DOMAIN_CLIENT: "https://{{ (index .Values.ingress.hosts 0).host }}"
  DOMAIN_SERVER: "https://{{ (index .Values.ingress.hosts 0).host }}"
  NO_INDEX: "true"
  CONSOLE_JSON: "false"
  DEBUG_LOGGING: "false"
  DEBUG_CONSOLE: "false"
  ENDPOINTS: "openAI,assistants,agents,gptPlugins,google,anthropic,custom"
  ANTHROPIC_MODELS: "claude-3-opus-latest,claude-3-5-sonnet-latest,claude-3-5-haiku-latest"
  ANTHROPIC_TITLE_MODEL: "claude-3-5-sonnet-latest"
  OPENAI_MODELS: "gpt-4o,gpt-4o-realtime-preview,gpt-4-turbo,gpt-4o-mini,o1-mini,gpt-4,dall-e-2,dall-e-3"
  DEBUG_OPENAI: "false"
  TITLE_CONVO: "true"
  OPENAI_TITLE_MODEL: "gpt-4o-mini"
  OPENAI_SUMMARIZE: "true"
  OPENAI_SUMMARY_MODEL: "gpt-4o-mini"
  PLUGIN_MODELS: "gpt-4o,gpt-4o-realtime-preview,gpt-4-turbo,gpt-4o-mini,o1-mini,gpt-4,"
  DEBUG_PLUGINS: "false"
  SEARCH: "false"
  MEILI_NO_ANALYTICS: "true"
  ALLOW_EMAIL_LOGIN: "true"
  ALLOW_REGISTRATION: "false"
  ALLOW_SOCIAL_LOGIN: "true"
  ALLOW_SOCIAL_REGISTRATION: "true"
  ALLOW_PASSWORD_RESET: "true"
  ALLOW_ACCOUNT_DELETION: "true"
  ALLOW_UNVERIFIED_EMAIL_LOGIN: "true"
  SESSION_EXPIRY: "1000 * 60 * 15"
  REFRESH_TOKEN_EXPIRY: "1000 * 60 * 60 * 24 * 7"
  STATIC_CACHE_MAX_AGE: "172800"
  STATIC_CACHE_S_MAX_AGE: "86400"
  DISABLE_COMPRESSION: "false"
  LIMIT_CONCURRENT_MESSAGES: "true"
  CONCURRENT_MESSAGE_MAX: "2"
  GITHUB_CALLBACK_URL: "/oauth/github/callback"
  GOOGLE_CALLBACK_URL: "/oauth/google/callback"
  SHOW_BIRTHDAY_ICON: "true"
