{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "librechat.fullname" . }}
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "librechat.selectorLabels" . | nindent 4 }}
  minAvailable: {{ .Values.pdb.minAvailable }}
{{- end }}
