apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ include "librechat.fullname" . }}-images-data'
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ include "librechat.fullname" . }}-uploads-data'
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ include "librechat.fullname" . }}-logs-data'
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ include "librechat.fullname" . }}-meilisearch-data'
  labels:
    {{- include "librechatMeilisearch.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
