apiVersion: v1
kind: Secret
metadata:
  name: '{{- include "librechat.fullname" . }}-secrets'
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
    avp.kubernetes.io/path: kv/data/lab/librechat
stringData:
  mongodb-password: "<MONGODB_PASSWORD>"
  mongodb-metrics-password: "<MONGODB_PASSWORD>"
  mongodb-passwords: "[<MONGODB_PASSWORD>]"
  mongodb-root-password: "<MONGODB_ROOT_PASSWORD>"
  MONGO_URI: "mongodb://root:<MONGODB_ROOT_PASSWORD>@{{ .Release.Name }}-mongodb:27017"
  ANTHROPIC_API_KEY: "<ANTHROPIC_API_KEY>"
  OPENAI_API_KEY: "<OPENAI_API_KEY>"
  JWT_SECRET: "<JWT_SECRET>"
  JWT_REFRESH_SECRET: "<JWT_REFRESH_SECRET>"
  CREDS_KEY: "<CREDS_KEY>"
  CREDS_IV: "<CREDS_IV>"
