repositories:
  - name: cockroachdb
    url: https://charts.cockroachdb.com/
  - name: zitadel
    url: https://charts.zitadel.com/

helmDefaults:
  timeout: 21600

releases:
  - name: crdb
    namespace: zitadel
    chart: cockroachdb/cockroachdb
    version: 14.0.4
    values:
      - ./crdb-values.yaml
  - name: zitadel
    namespace: zitadel
    chart: zitadel/zitadel
    version: 8.5.0
    values:
      - ./values.yaml
    set:
      - value: ref+vault://kv/lab/zitadel#MASTER_KEY
        name: zitadel.masterkey
