apiVersion: v1
kind: Secret
metadata:
  name: zitadel-secrets
  annotations:
    avp.kubernetes.io/path: kv/data/lab/zitadel
stringData:
  masterkey: "<MASTER_KEY>"
  config-yaml: |
    ExternalSecure: true
    ExternalPort: 443
    ExternalDomain: zitadel.lab.kvd.studio
    TLS:
      Enabled: false
    Machine:
      Identification:
        Hostname:
          Enabled: true
        Webhook:
          Enabled: false
    Telemetry:
      Enabled: false
    Database:
      cockroach:
        Host: crdb
