apiVersion: v1
kind: ConfigMap
metadata:
  name: time-machine-configmap
  labels:
    {{- include "time-machine.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
data:
  DJANGO_SETTINGS_MODULE: "time_machine.settings"
  POSTGRESQL_HOST: "postgres-postgresql"
  POSTGRESQL_PORT: "5432"
  POSTGRESQL_USERNAME: "timemachine-client"
  POSTGRESQL_DATABASE: "timemachine"
