apiVersion: v1
kind: Secret
metadata:
  name: time-machine-secrets
  labels:
    {{- include "time-machine.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    avp.kubernetes.io/path: kv/data/lab/time-machine
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "<DJANGO_SECRET_KEY>"
  DJANGO_SUPERUSER_EMAIL: "<DJANGO_SUPERUSER_EMAIL>"
  DJANGO_SUPERUSER_PASSWORD: "<DJANGO_SUPERUSER_PASSWORD>"
  DJANGO_SUPERUSER_USERNAME: "<DJANGO_SUPERUSER_USERNAME>"
  POSTGRESQL_PASSWORD: "<POSTGRESQL_PASSWORD>"
