repositories:
  - name: infisical
    url: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/

releases:
  - name: manifests
    namespace: infisical2
    chart: ./manifests
  - name: infisical
    chart: infisical/infisical-standalone
    version: 1.5.0
    namespace: infisical2
    values:
      - values.yaml
