repositories:
  - name: infisical
    url: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/

releases:
  - name: manifests
    namespace: infisical2
    chart: ./manifests
  - name: infisical
    chart: infisical/infisical-standalone
    version: 1.7.3
    namespace: infisical2
    values:
      - values.yaml
  - name: infisical-operator
    chart: infisical/secrets-operator
    version: 0.10.28
    namespace: infisical2
    values:
      - operator-values.yaml
