- name: Setup K3s master node
  hosts: k8s_master
  become: true

  tasks:
    - name: Install K3s
      shell:
        curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=v1.26 sh -s - server --cluster-init --write-kubeconfig-mode 644 --disable traefik --docker

    - name: Get kubeconfig
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ../outputs/kubeconfig.yaml
        flat: true

    - name: Get node token
      fetch:
        src: /var/lib/rancher/k3s/server/node-token
        dest: ../outputs/node-token
        flat: true
