- name: Initial setup of VMs
  hosts: rpi5
  become: true

  tasks:
    - name: Update apt
      ansible.builtin.apt:
        update_cache: true
        upgrade: true

    - name: Install basics
      ansible.builtin.package:
        name:
          - curl
          - wget
          - gnupg
          - ca-certificates
          - apt-transport-https
          - btop
          - htop
          - neofetch
          - neovim
          - nfs-common
          - policycoreutils
          - open-iscsi
          - vim
        state: latest

    - name: Remove conflicting Docker packages
      ansible.builtin.package:
        name:
          - docker.io
          - docker-doc
          - docker-compose
          - podman-docker
          - containerd
          - runc
        state: absent

    - name: Add Docker GPG key and repository
      ansible.builtin.shell:
        cmd: |
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg
          sudo chmod a+r /etc/apt/keyrings/docker.gpg
          echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Update apt with new sources
      ansible.builtin.apt:
        update_cache: true
        upgrade: true

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest

    - name: Update default Docker daemon.json
      ansible.builtin.copy:
        src: ../files/daemon.json
        dest: /etc/docker
        force: true
        mode: '644'

    - name: Restart Docker daemon
      ansible.builtin.service:
        name: docker
        state: restarted

    - name: Create Docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to Docker group
      ansible.builtin.user:
        name: kvdomingo
        append: true
        groups:
          - docker
