- name: Initial setup of VMs
  hosts: gitea_runners

  tasks:
    - name: Update apt
      apt:
        update_cache: true
        upgrade: yes

    - name: Install basics
      package:
        name:
          - curl
          - wget
          - gnupg
          - ca-certificates
          - apt-transport-https
          - vim
          - sudo
        state: latest

    - name: Add Docker GPG key and repository
      shell:
        cmd: |
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg
          sudo chmod a+r /etc/apt/keyrings/docker.gpg
          echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Update apt with new sources
      apt:
        update_cache: true
        upgrade: yes

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest

    - name: Update default Docker daemon.json
      copy:
        src: ../files/daemon.json
        dest: /etc/docker
        force: true

    - name: Restart Docker daemon
      service:
        name: docker
        state: restarted

    - name: Clone gitea-runner config
      git:
        repo: https://github.com/kvdomingo/homelab-gitea-actions
        dest: ~/gitea-act
        clone: true
