- name: Setup K3s worker nodes
  hosts: k8s_workers
  become: true
  vars:
    K8S_VERSION: 1.30

  tasks:
    - name: Increase inotify values
      shell: |
        sysctl fs.inotify.max_user_instances=2099999999
        sysctl fs.inotify.max_user_watches=2099999999
        sysctl fs.inotify.max_queued_events=2099999999

    - name: Install K3s
      shell: >
        curl -sfL https://get.k3s.io |
        INSTALL_K3S_CHANNEL=v{{ K8S_VERSION }}
        K3S_TOKEN={{ lookup('ansible.builtin.env', 'K3S_NODE_TOKEN') }}
        sh -s - server
        --server https://srv-k8s-01.lab:6443
        --disable traefik
        --docker
