services:
  runner:
    image: drone/drone-runner-docker:1
    restart: unless-stopped
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  vault-plugin:
    image: drone/vault:1
    restart: unless-stopped
    env_file: .env
