apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "plausible.fullname" . }}-configmap'
  labels:
    {{- include "plausible.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  TMPDIR: "/var/lib/plausible/tmp"
  BASE_URL: "{{ (index .Values.ingress.hosts 0).host }}"
  DISABLE_REGISTRATION: "false"
  ENABLE_EMAIL_VERIFICATION: "false"
  HTTP_PORT: "{{ .Values.service.port }}"
