apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "plausible.fullname" . }}-secrets'
  labels:
    {{- include "plausible.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
    avp.kubernetes.io/path: kv/data/lab/plausible
type: Opaque
stringData:
  SECRET_KEY_BASE: "<SECRET_KEY_BASE>"
  TOTP_VAULT_KEY: "<TOTP_VAULT_KEY>"
  DATABASE_URL: "<DATABASE_URL>"
  CLICKHOUSE_DATABASE_URL: "<CLICKHOUSE_DATABASE_URL>"
