apiVersion: v1
kind: Secret
metadata:
  name: plausible-secrets
  labels:
    {{- include "plausible.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    avp.kubernetes.io/path: kv/data/lab/plausible
type: Opaque
stringData:
  POSTGRESQL_PASSWORD: "<POSTGRESQL_PASSWORD>"
  CLICKHOUSE_PASSWORD: "<CLICKHOUSE_PASSWORD>"
  SECRET_KEY_BASE: "<SECRET_KEY>"
  DATABASE_URL: "postgres://plausible:<POSTGRESQL_PASSWORD>@plausible-postgresql-hl:5432/plausible_db"
  CLICKHOUSE_DATABASE_URL: "http://plausible:<CLICKHOUSE_PASSWORD>@plausible-clickhouse-headless:8123/plausible_events_db"
