repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: manifests
    namespace: argocd
    chart: ./manifests
  - name: argocd
    namespace: argocd
    chart: argo/argo-cd
    version: 8.0.0
    values:
      - values.yaml
