apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-config
  namespace: arrstack
  labels:
    app.kubernetes.io/name: calibre
    app.kubernetes.io/part-of: arrstack
  annotations:
    helm.sh/resource-policy: keep
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-data
  namespace: arrstack
  labels:
    app.kubernetes.io/name: calibre
    app.kubernetes.io/part-of: arrstack
  annotations:
    helm.sh/resource-policy: keep
spec:
  resources:
    requests:
      storage: 64Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
