apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.27.0
    chart: vault
    helm:
      releaseName: vault
      valuesObject:
        injector:
          metrics:
            enabled: true
        server:
          ingress:
            enabled: true
            annotations:
              gethomepage.dev/enabled: "true"
              gethomepage.dev/name: "Vault"
              gethomepage.dev/group: "Security"
              gethomepage.dev/icon: "vault.png"
              gethomepage.dev/ping: "vault.lab.kvd.studio"
            hosts:
              - host: vault.lab.kvd.studio
        ha:
          enabled: true
          raft:
            enabled: true
        ui:
          enabled: true
        csi:
          enabled: true
        serverTelemetry:
          serviceMonitor:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
