apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "actual-budget.fullname" . }}-data
  labels:
    {{- include "actual-budget.labels" . | nindent 4 }}
  {{- with .Values.persistence.data.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.persistence.data.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
