apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "renovate.fullname" . }}-configmap'
  labels:
    {{- include "renovate.labels" . | nindent 4 }}
data:
  config.json5: |-
    {
      "globalExtends": [
        "config:recommended",
        ":semanticCommits",
      ],
      "onboarding": true,
      "repositories": [
        "kvdomingo/banyuhay",
        "kvdomingo/hannibot",
      ],
      "packageRules": [
        {
          "matchPackageNames": [
            "python",
          ],
          "matchUpdateTypes": [
            "minor",
          ],
          "enabled": false,
        }
      ]
    }
