apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firefly
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git.lab.kvd.studio/r/homelab.git
    targetRevision: main
    chart: firefly/firefly
  destination:
    server: https://kubernetes.default.svc
    namespace: firefly
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
