apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cloudflare-inf-secret
  labels: { }
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  syncConfig:
    resyncInterval: 10s
  authentication:
    kubernetesAuth:
      identityId: ea9c7e43-4921-4cac-bac7-8fc8b1a24440
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: infisical2
      secretsScope:
        projectSlug: cloudflare
        envSlug: prod
        secretsPath: /
        recursive: true
  managedKubeSecretReferences:
    - secretName: cloudflare-secrets
      secretNamespace: cloudflare
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        metadata:
          annotations:
            helm.sh/hook: pre-install,pre-upgrade
            helm.sh/hook-weight: "-5"
            helm.sh/hook-delete-policy: before-hook-creation
        data:
          credentials.json: |-
            {
              "AccountTag": "{{ .CLOUDFLARE_ACCOUNT_NUMBER.Value }}",
              "TunnelID": "{{ .CLOUDFLARE_TUNNEL_ID.Value }}",
              "TunnelSecret": "{{ .CLOUDFLARE_TUNNEL_SECRET.Value }}"
            }
