apiVersion: v1
kind: Secret
metadata:
  name: '{{- include "discdevbot.fullname" . }}-secrets'
  labels:
    {{- include "discdevbot.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
    avp.kubernetes.io/path: kv/data/lab/discdevbot
stringData:
  DISCORD_TOKEN: "<DISCORD_TOKEN>"
  TEST_GUILD_ID: "<TEST_GUILD_ID>"
