apiVersion: v1
kind: Secret
metadata:
  name: apod-secrets
  labels:
    app: apod
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    avp.kubernetes.io/path: kv/data/lab/apod
type: Opaque
stringData:
  NASA_APOD_API_KEY: "<NASA_APOD_API_KEY>"
