apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git.lab.kvd.studio/r/homelab.git
    targetRevision: main
    path: apod/apod
    plugin:
      name: argocd-vault-plugin-helm
  destination:
    server: https://kubernetes.default.svc
    namespace: apod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
