{{- if .Values.config.files }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "importer.fullname" . }}-files
  labels:
    {{- include "importer.labels" . | nindent 4 }}
data:
{{- range .Values.config.files }}
  {{ .name }}: {{ .content | b64enc }}
{{- end }}
{{- end }}
