{{- if not .Values.fireflyiii.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "importer.fullname" . }}
  labels:
    {{- include "importer.labels" . | nindent 4 }}
data:
  accessToken: {{ .Values.fireflyiii.auth.accessToken | b64enc | quote }}
{{- end }}
