- name: Setup K3s master node
  hosts: rpi5_workers
  become: true

  tasks:
    - name: Uninstall K3s
      ansible.builtin.command: /usr/local/bin/k3s-agent-uninstall.sh
      changed_when: false
      ignore_errors: true

    - name: Reboot
      ansible.builtin.reboot:
