apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-tracker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git.lab.kvd.studio/r/homelab.git
    targetRevision: main
    path: go-tracker/go-tracker
    plugin:
      name: argocd-vault-plugin-helm
  destination:
    server: https://kubernetes.default.svc
    namespace: go-tracker
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
