services:
  api:
    build: .
    image: git.lab.kvd.studio/r/go-tracker-api:${SHORT_SHA}
    init: true
    env_file: ./api/.env
    volumes:
      - ./api:/app
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy

  ui:
    image: oven/bun:1.0-alpine
    environment:
      NODE_ENV: development
    working_dir: /app
    init: true
    command:
      - /bin/sh
      - "-c"
      - "bun install && exec bun run dev"
    volumes:
      - ./ui:/app
    ports:
      - 3000:3000

  db:
    image: bitnami/postgresql:16.1.0-debian-11-r16
    init: true
    env_file: ./api/.env
    volumes:
      - db-data:/bitnami/postgresql
    ports:
      - 5432:5432
    healthcheck:
      test:
        - CMD
        - /bin/sh
        - -c
        - >
          pg_isready --host localhost --port 5432
          -U gotracker -d gotracker
      interval: 3s
      retries: 10
      start_period: 10s
      timeout: 3s

volumes:
  db-data: { }
