networks:
  gateway:
    external: true

volumes:
  db-data:

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: kvdomingo/go-tracker-prod:latest
    init: true
    env_file: .env.prod
    restart: unless-stopped
    depends_on:
      - redis

  celery-worker:
    image: kvdomingo/go-tracker-prod:latest
    env_file: .env.prod
    init: true
    command:
      - celery
      - "-A"
      - go_tracker.tasks
      - worker
      - "--loglevel=INFO"
    restart: unless-stopped
    depends_on:
      - redis
      - backend

  celery-beat:
    image: kvdomingo/go-tracker-prod:latest
    env_file: .env.prod
    init: true
    command:
      - celery
      - "-A"
      - go_tracker.tasks
      - beat
    restart: unless-stopped
    depends_on:
      - redis
      - backend

  redis:
    image: redis/redis-stack-server:latest
    volumes:
      - db-data:/data
    restart: unless-stopped

  proxy:
    image: bitnami/nginx:latest
    volumes:
      - ./proxy/prod:/opt/bitnami/nginx/conf/server_blocks:ro
    environment:
      - NGINX_HTTP_PORT_NUMBER=${PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gotracker.rule=Host(`go-tracker.localhost`)"
      - "traefik.http.routers.gotracker.entrypoints=http"
      - "traefik.http.routers.gotracker.middlewares=secured@file"
      - "traefik.docker.network=gateway"
      - "traefik.http.services.gotracker.loadbalancer.server.port=${PORT}"
    networks:
      - default
      - gateway
    restart: unless-stopped
    depends_on:
      - backend
