apiVersion: v1
kind: Secret
metadata:
  name: {{ include "umami.fullname" . }}-secrets
  labels:
    {{- include "umami.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
    avp.kubernetes.io/path: kv/data/lab/umami
type: Opaque
stringData:
  POSTGRESQL_PASSWORD: "<POSTGRESQL_PASSWORD>"
  DATABASE_URL: "<DATABASE_URL>"
