apiVersion: v1
kind: Secret
metadata:
  name: '{{- include "unreceiptify.fullname" . }}-secrets'
  labels:
    {{- include "unreceiptify.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
    avp.kubernetes.io/path: kv/data/lab/unreceiptify
type: Opaque
stringData:
  AZURE_AI_ACCESS_KEY: "<AZURE_AI_ACCESS_KEY>"
  AZURE_AI_ENDPOINT: "<AZURE_AI_ENDPOINT>"
