apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{- include "firefly.fullname" . }}-configmap'
  labels:
    {{- include "firefly.labels" . | nindent 4 }}
data:
  DB_CONNECTION: "pgsql"
  DB_HOST: '{{- include "firefly.fullname" . }}-postgresql'
  DB_PORT: "5432"
  DB_USERNAME: "firefly"
  DB_DATABASE: "firefly"
  APP_ENV: "production"
  TZ: "Asia/Manila"
  TRUSTED_PROXIES: "**"
  REDIS_HOST: '{{- include "firefly.fullname" . }}-redis-headless'
  REDIS_PORT: "6379"
  CACHE_DRIVER: "redis"
  SESSION_DRIVER: "redis"
  ENABLE_EXTERNAL_RATES: "true"
  MAP_DEFAULT_LAT: "14.60"
  MAP_DEFAULT_LONG: "120.97"
  APP_URL: "https://{{ (index .Values.ingress.hosts 0).host }}"
