apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "firefly.fullname" . }}-configmap'
  labels:
    {{ include "firefly.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  DB_CONNECTION: "pgsql"
  DB_HOST: '10.10.10.103'
  DB_PORT: "5432"
  DB_USERNAME: "firefly"
  DB_DATABASE: "firefly"
  APP_ENV: "production"
  TZ: "Asia/Manila"
  TRUSTED_PROXIES: "**"
  REDIS_HOST: '{{ include "firefly.fullname" . }}-redis-headless'
  REDIS_PORT: "6379"
  CACHE_DRIVER: "redis"
  SESSION_DRIVER: "redis"
  ENABLE_EXTERNAL_RATES: "true"
  MAP_DEFAULT_LAT: "14.60"
  MAP_DEFAULT_LONG: "120.97"
  APP_URL: "https://{{ (index .Values.ingress.hosts 0).host }}"
  MAIL_MAILER: "smtp"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_ENCRYPTION: "tls"
