apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{- include "firefly.fullname" . }}-configmap'
  labels:
    {{- include "firefly.labels" . | nindent 4 }}
data:
  DB_CONNECTION: "pgsql"
  DB_HOST: '{{- include "firefly.fullname" . }}-postgresql'
  DB_PORT: "5432"
  DB_USERNAME: "firefly"
  DB_DATABASE: "firefly"
