apiVersion: v1
kind: Secret
metadata:
  name: '{{- include "firefly.fullname" . }}-secrets'
  labels:
    {{- include "firefly.labels" . | nindent 4 }}
  annotations:
    avp.kubernetes.io/path: kv/data/lab/firefly
type: Opaque
stringData:
  APP_KEY: "<APP_KEY>"
  DB_PASSWORD: "<POSTGRESQL_PASSWORD>"
  STATIC_CRON_TOKEN: "<STATIC_CRON_TOKEN>"
