apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "firefly.fullname" . }}-secrets'
  labels:
    {{ include "firefly.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
    avp.kubernetes.io/path: kv/data/lab/firefly
type: Opaque
stringData:
  APP_KEY: "<APP_KEY>"
  DB_PASSWORD: "<POSTGRESQL_PASSWORD>"
  STATIC_CRON_TOKEN: "<STATIC_CRON_TOKEN>"
  SITE_OWNER: "<SITE_OWNER>"
  REDIS_PASSWORD: "<REDIS_PASSWORD>"
  MAIL_FROM: "<SITE_OWNER>"
  MAIL_USERNAME: "<SITE_OWNER>"
  MAIL_PASSWORD: "<MAIL_PASSWORD>"
