apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: arrstack
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/part-of: arrstack
  annotations:
    helm.sh/resource-policy: keep
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads
  namespace: arrstack
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/part-of: arrstack
  annotations:
    helm.sh/resource-policy: keep
spec:
  resources:
    requests:
      storage: 512Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
