- name: Setup NVIDIA container toolkit
  become: true
  block:
    - name: Download NVCT GPG key
      ansible.builtin.get_url:
        url: https://nvidia.github.io/libnvidia-container/gpgkey
        dest: /tmp/nvidia.gpg
        mode: "0644"
    - name: Import NVCT GPG key
      ansible.builtin.command:
        cmd: gpg --dearmor --yes -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg /tmp/nvidia.gpg
      register: gpg_import
      changed_when: gpg_import.rc == 0
    - name: Set permissions for NVCT GPG key
      ansible.builtin.file:
        path: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
        mode: "0644"
    - name: Get NVCT repo list
      ansible.builtin.get_url:
        url: https://nvidia.github.io/libnvidia-container/stable/dev/nvidia-container-toolkit.list
        dest: /etc/apt/sources.list.d/nvidia-container-toolkit.list
        mode: "0644"
    - name: Edit NVCT repo list
      ansible.builtin.replace:
        path: /etc/apt/sources.list.d/nvidia-container-toolkit.list
        regexp: 'deb https://'
        replace: 'deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://'
    - name: Update apt
      ansible.builtin.apt:
        update_cache: true
    - name: Install NVCT
      ansible.builtin.package:
        name: nvidia-container-toolkit
        state: latest
