- name: Download JetBrains Toolbox
  ansible.builtin.get_url:
    url: https://download.jetbrains.com/toolbox/{{ jetbrains_toolbox_version }}.tar.gz
    dest: "{{ USER_HOME }}/Downloads/{{ jetbrains_toolbox_version }}.tar.gz"
    mode: '644'

- name: Untar JetBrains Toolbox
  ansible.builtin.unarchive:
    src: "{{ USER_HOME }}/Downloads/{{ jetbrains_toolbox_version }}.tar.gz"
    dest: "{{ USER_HOME }}/Downloads"

- name: Install JetBrains Toolbox
  ansible.builtin.command:
    chdir: "{{ USER_HOME }}/Downloads/{{ jetbrains_toolbox_version }}"
    cmd: ./jetbrains-toolbox
    creates: "{{ USER_HOME }}/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox"
