repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: manifests
    namespace: postgres
    chart: ./manifests
  - name: pg
    namespace: postgres
    chart: bitnami/postgresql-ha
    version: 15.1.6
    values:
      - values.yaml
    set:
      - value: ref+vault://kv/lab/postgres#POSTGRESQL_PASSWORD
        name: postgresql.password
      - value: ref+vault://kv/lab/postgres#REPMGR_PASSWORD
        name: postgresql.repmgrPassword
      - value: ref+vault://kv/lab/postgres#PGPOOL_PASSWORD
        name: pgpool.adminPassword
      - value: ref+vault://kv/lab/postgres#PGPOOL_CUSTOM_USERNAMES
        name: pgpool.customUsers.usernames
      - value: ref+vault://kv/lab/postgres#PGPOOL_CUSTOM_PASSWORDS
        name: pgpool.customUsers.passwords
