apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{- include "tandoor.fullname" . }}-static'
  labels:
    {{- include "tandoor.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{- include "tandoor.fullname" . }}-media'
  labels:
    {{- include "tandoor.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
