apiVersion: v1
kind: Secret
metadata:
  name: '{{- include "tandoor.fullname" . }}-secrets'
  labels:
    {{- include "tandoor.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
    avp.kubernetes.io/path: kv/data/lab/tandoor
stringData:
  POSTGRES_PASSWORD: "<POSTGRESQL_PASSWORD>"
  SECRET_KEY: "<SECRET_KEY>"
