{{- if not .Values.disableKeel }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keel
  namespace: {{ include "apps.argocdNamespace" . | quote }}
  finalizers:
    {{- include "apps.finalizers" . | nindent 4 }}
spec:
  project: {{ .Values.project }}
  source:
    repoURL: https://charts.keel.sh
    chart: keel
    targetRevision: 1.0.3
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            helmProvider:
              enabled: true
              version: v3
            discord:
              enabled: true
              webhookUrl: "<path:kv/data/lab/keel#DISCORD_WEBHOOK>"
            podDisruptionBudget:
              enabled: true
              minAvailable: 2
            ingress:
              enabled: true
              annotations:
                gethomepage.dev/enabled: "true"
                gethomepage.dev/name: "Keel"
                gethomepage.dev/group: "CI/CD"
                gethomepage.dev/icon: "si-keepachangelog"
                gethomepage.dev/ping: "keel.{{ .Values.ingress.baseDomain }}"
              hosts:
                - host: "keel.{{ .Values.ingress.baseDomain }}"
                  paths: [ "/" ]
  destination:
    server: {{ .Values.destination.server }}
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
