{{- if not .Values.disablePromstack }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promstack
  namespace: {{ include "apps.argocdNamespace" . | quote }}
  finalizers:
    {{- include "apps.finalizers" . | nindent 4 }}
spec:
  project: {{ .Values.project }}
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 58.2.2
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            crds:
              enabled: true
            alertmanager:
              podDisruptionBudget:
                enabled: true
                minAvailable: 1
              ingress:
                enabled: true
                annotations:
                  gethomepage.dev/enabled: "true"
                  gethomepage.dev/name: "Alertmanager"
                  gethomepage.dev/group: "Monitoring"
                  gethomepage.dev/icon: "alertmanager.png"
                  gethomepage.dev/ping: "alertmanager.{{ .Values.ingress.baseDomain }}"
                hosts:
                  - "alertmanager.{{ .Values.ingress.baseDomain }}"
                paths: [ "/" ]
              config:
                route:
                  receiver: discord
                  group_by: [ 'namespace' ]
                  group_wait: 30s
                  group_interval: 5m
                  repeat_interval: 12h
                  routes:
                    - receiver: discord
                      matchers:
                        - alertname="Watchdog"
                receivers:
                  - name: discord
                    discord_configs:
                      - webhook_url: "<path:kv/data/lab/promstack#DISCORD_WEBHOOK_URL>"
                        # title:
                        # message:
            grafana:
              adminPassword: "<path:kv/data/lab/promstack#GRAFANA_PASSWORD>"
              ingress:
                enabled: true
                annotations:
                  gethomepage.dev/enabled: "true"
                  gethomepage.dev/name: "Grafana"
                  gethomepage.dev/group: "Monitoring"
                  gethomepage.dev/icon: "grafana.png"
                  gethomepage.dev/ping: "grafana.{{ .Values.ingress.baseDomain }}"
                  gethomepage.dev/widget.type: "grafana"
                  gethomepage.dev/widget.url: "https://grafana.{{ .Values.ingress.baseDomain }}"
                  gethomepage.dev/widget.username: "admin"
                  gethomepage.dev/widget.password: "<path:kv/data/lab/promstack#GRAFANA_PASSWORD>"
                hosts:
                  - "grafana.{{ .Values.ingress.baseDomain }}"
              sidecar:
                dashboards:
                  enableNewTablePanelSyntax: true
                datasources:
                  url: http://promstack-kube-prometheus-prometheus:9090/
            kube-state-metrics:
              selfMonitor:
                enabled: true
            prometheus:
              thanosService:
                enabled: true
              thanosServiceMonitor:
                enabled: true
              podDisruptionBudget:
                enabled: true
                minAvailable: 1
              prometheusSpec:
                scrapeInterval: 3m
                retention: 14d
                externalUrl: https://prometheus.{{ .Values.ingress.baseDomain }}
                ruleSelectorNilUsesHelmValues: false
                serviceMonitorSelectorNilUsesHelmValues: false
                podMonitorSelectorNilUsesHelmValues: false
                tsdb:
                  outOfOrderTimeWindow: 10m
              ingress:
                enabled: true
                annotations:
                  gethomepage.dev/enabled: "true"
                  gethomepage.dev/name: "Prometheus"
                  gethomepage.dev/group: "Monitoring"
                  gethomepage.dev/icon: "prometheus.png"
                  gethomepage.dev/ping: "prometheus.{{ .Values.ingress.baseDomain }}"
                  gethomepage.dev/widget.type: "prometheus"
                  gethomepage.dev/widget.url: "https://prometheus.{{ .Values.ingress.baseDomain }}"
                hosts:
                  - "prometheus.{{ .Values.ingress.baseDomain }}"
                paths: [ "/" ]
            prometheusOperator:
              admissionWebhooks:
                failurePolicy: Ignore
  destination:
    server: {{ .Values.destination.server }}
    namespace: promstack
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
