{{- if not .Values.disableReflector }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  namespace: {{ include "apps.argocdNamespace" . | quote }}
  finalizers:
    {{- include "apps.finalizers" . | nindent 4 }}
spec:
  project: {{ .Values.project }}
  source:
    repoURL: https://emberstack.github.io/helm-charts
    chart: reflector
    targetRevision: 7.1.262
    helm:
      releaseName: reflector
      valuesObject:
        replicaCount: 4
  destination:
    server: {{ .Values.destination.server }}
    namespace: reflector
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
