{{- if (.Values.vault.enabled | default true) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: {{ include "apps.argocdNamespace" . | quote }}
  finalizers:
    {{- include "apps.finalizers" . | nindent 4 }}
spec:
  project: {{ .Values.project }}
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.27.0
    helm:
      releaseName: vault
      valuesObject:
        injector:
          metrics:
            enabled: true
        server:
          ingress:
            enabled: true
            annotations:
              gethomepage.dev/enabled: "true"
              gethomepage.dev/name: "Vault Backup"
              gethomepage.dev/group: "Security"
              gethomepage.dev/icon: "vault.png"
              gethomepage.dev/ping: "vault2.lab.kvd.studio"
            hosts:
              - host: vault2.lab.kvd.studio
          auditStorage:
            enabled: true
          standalone:
            enabled: false
          ha:
            enabled: true
            raft:
              enabled: true
        ui:
          enabled: true
        csi:
          enabled: true
        serverTelemetry:
          serviceMonitor:
            enabled: true
  destination:
    server: {{ .Values.destination.server }}
    namespace: vault2
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
