{{- if not .Values.disableZitadel }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zitadel
  namespace: {{ include "apps.argocdNamespace" . | quote }}
  finalizers:
    {{- include "apps.finalizers" . | nindent 4 }}
spec:
  project: {{ .Values.project }}
  sources:
    - repoURL: https://charts.cockroachdb.com/
      chart: cockroachdb
      targetRevision: 12.0.4
      plugin:
        name: argocd-vault-plugin-helm
        env:
          - name: HELM_VALUES
            value: |
              fullnameOverride: crdb
              tls:
                enabled: false
              prometheus:
                enabled: true
              serviceMonitor:
                enabled: true
    - repoURL: https://charts.zitadel.com
      chart: zitadel
      targetRevision: 7.12.1
      plugin:
        name: argocd-vault-plugin-helm
        env:
          - name: HELM_VALUES
            value: |
              zitadel:
                configSecretName: zitadel-secrets
                masterkeySecretName: zitadel-secrets
              ingress:
                enabled: true
                annotations:
                  gethomepage.dev/enabled: "true"
                  gethomepage.dev/name: "Zitadel"
                  gethomepage.dev/group: "Admin"
                  gethomepage.dev/icon: "zitadel.png"
                  gethomepage.dev/ping: "zitadel.{{ .Values.ingress.baseDomain }}"
                hosts:
                  - host: zitadel.{{ .Values.ingress.baseDomain }}
                    paths:
                      - path: /
                        pathType: Prefix
              metrics:
                enabled: true
                serviceMonitor:
                  enabled: true
                  honorLabels: true
              pdb:
                enabled: true
                minAvailable: 1
    - repoURL: https://git.lab.kvd.studio/r/homelab
      targetRevision: main
      path: zitadel
      plugin:
        name: argocd-vault-plugin
  destination:
    server: {{ .Values.destination.server }}
    namespace: zitadel
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
