{{- if not .Values.disableAirbyte }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airbyte
  namespace: {{ include "apps.argocdNamespace" . | quote }}
  finalizers:
    {{- include "apps.finalizers" . | nindent 4 }}
spec:
  project: {{ .Values.project }}
  source:
    repoURL: https://airbytehq.github.io/helm-charts
    chart: airbyte
    targetRevision: 1.0.0
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            global:
              airbyteUrl: airbyte.{{ .Values.ingress.baseDomain }}
              auth:
                enabled: true
                firstName: "<path:kv/data/lab/airbyte#ADMIN_FIRST_NAME>"
                lastName: "<path:kv/data/lab/airbyte#ADMIN_LAST_NAME>"
              database:
                password: "<path:kv/data/lab/airbyte#POSTGRESQL_PASSWORD>"
            webapp:
              ingress:
                enabled: true
                annotations:
                  gethomepage.dev/enabled: "true"
                  gethomepage.dev/name: "Airbyte"
                  gethomepage.dev/group: "DataOps"
                  gethomepage.dev/icon: "si-airbyte"
                  gethomepage.dev/ping: "airbyte.{{ .Values.ingress.baseDomain }}"
                hosts:
                  - host: airbyte.{{ .Values.ingress.baseDomain }}
                    paths:
                      - path: /
                        pathType: Prefix
            metrics:
              enabled: true
            postgresql:
              postgresqlPassword: "<path:kv/data/lab/airbyte#POSTGRESQL_PASSWORD>"
            keycloak:
              auth:
                adminUsername: "<path:kv/data/lab/airbyte#KEYCLOAK_ADMIN_USERNAME>"
                adminPassword: "<path:kv/data/lab/airbyte#KEYCLOAK_ADMIN_PASSWORD>"
  destination:
    server: {{ .Values.destination.server }}
    namespace: airbyte
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
