{{- if not .Values.disableCloudflareTunnel }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare
  namespace: {{ include "apps.argocdNamespace" . | quote }}
  finalizers:
    {{- include "apps.finalizers" . | nindent 4 }}
spec:
  project: {{ .Values.project }}
  source:
    repoURL: https://cloudflare.github.io/helm-charts
    chart: cloudflare-tunnel
    targetRevision: 0.3.0
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            cloudflare:
              account: <path:kv/data/lab/cloudflare#CLOUDFLARE_ACCOUNT_NUMBER>
              tunnelName: <path:kv/data/lab/cloudflare#CLOUDFLARE_TUNNEL_NAME>
              tunnelId: <path:kv/data/lab/cloudflare#CLOUDFLARE_TUNNEL_ID>
              secret: <path:kv/data/lab/cloudflare#CLOUDFLARE_TUNNEL_TOKEN>
              ingress: [ ]
            image:
              tag: 2024.6.1
            replicaCount: 3
            resources:
              limits:
                cpu: 100m
                memory: 128Mi
              requests:
                cpu: 100m
                memory: 128Mi
  destination:
    server: {{ .Values.destination.server }}
    namespace: cloudflare
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
