{{- if not .Values.disableGoTracker }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-tracker
  namespace: {{ include "apps.argocdNamespace" . | quote }}
  finalizers:
    {{- include "apps.finalizers" . | nindent 4 }}
spec:
  project: {{ .Values.project }}
  source:
    repoURL: https://git.lab.kvd.studio/r/homelab.git
    targetRevision: main
    path: go-tracker
    plugin:
      name: argocd-vault-plugin-helm
  destination:
    server: {{ .Values.destination.server }}
    namespace: go-tracker
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
