{{- if not .Values.disableKestra }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kestra
  namespace: {{ include "apps.argocdNamespace" . | quote }}
  finalizers:
    {{- include "apps.finalizers" . | nindent 4 }}
spec:
  project: {{ .Values.project }}
  source:
    repoURL: https://helm.kestra.io/
    chart: kestra
    targetRevision: 0.20.7
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            deployments:
              webserver:
                enabled: true
              executor:
                enabled: true
              indexer:
                enabled: true
              scheduler:
                enabled: true
              worker:
                enabled: true
              standalone:
                enabled: false
            minio:
              enabled: true
              auth:
                rootUser: "<path:kv/data/lab/kestra#MINIO_ROOT_USER>"
                rootPassword: "<path:kv/data/lab/kestra#MINIO_ROOT_PASSWORD>"
            postgresql:
              enabled: true
              auth:
                password: "<path:kv/data/lab/kestra#POSTGRESQL_PASSWORD>"
              primary:
                readinessProbe:
                  enabled: false
                livenessProbe:
                  enabled: true
                  periodSeconds: 20
                  timeoutSeconds: 3
                  successThreshold: 1
                  failureThreshold: 3
                  initialDelaySeconds: 30
                startupProbe:
                  enabled: true
                  periodSeconds: 10
                  timeoutSeconds: 3
                  successThreshold: 1
                  failureThreshold: 60
                  initialDelaySeconds: 30
                persistence:
                  annotations:
                    argocd.argoproj.io/sync-options: Delete=false,Prune=false
            ingress:
              enabled: true
              annotations:
                gethomepage.dev/enabled: "true"
                gethomepage.dev/name: "Kestra"
                gethomepage.dev/group: "Orchestration"
                gethomepage.dev/icon: "kestra.png"
                gethomepage.dev/ping: "https://kestra.lab.kvd.studio"
              hosts:
                - host: kestra.lab.kvd.studio
                  paths:
                    - path: /
                      pathType: Prefix
  destination:
    server: {{ .Values.destination.server }}
    namespace: kestra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
