{{- if not .Values.disableMaybe }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maybe
  namespace: {{ include "apps.argocdNamespace" . | quote }}
  finalizers:
    {{- include "apps.finalizers" . | nindent 4 }}
spec:
  project: {{ .Values.project }}
  sources:
    - repoURL: https://git.lab.kvd.studio/r/homelab.git
      targetRevision: main
      path: maybe/helm
      helm:
        releaseName: maybe
    - repoURL: https://git.lab.kvd.studio/r/homelab.git
      targetRevision: main
      path: maybe/argocd
      plugin:
        name: argocd-vault-plugin
  destination:
    server: {{ .Values.destination.server }}
    namespace: maybe
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
