{{- if not .Values.disableMinio }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: {{ include "apps.argocdNamespace" . | quote }}
  finalizers:
    {{- include "apps.finalizers" . | nindent 4 }}
spec:
  project: {{ .Values.project }}
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 17.0.21
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            image:
              repository: bitnamilegacy/minio
              tag: 2025.7.23-debian-12-r5
            clientImage:
              repository: bitnamilegacy/minio-client
              tag: 2025.7.21-debian-12-r3
            auth:
              rootUser: "<path:kv/data/lab/minio#ROOT_USERNAME>"
              rootPassword: "<path:kv/data/lab/minio#ROOT_PASSWORD>"
              forceNewKeys: true
            mode: distributed
            statefulset:
              replicaCount: 4
              zones: 1
              drivesPerNode: 4
            livenessProbe:
              enabled: true
              initialDelaySeconds: 20
              periodSeconds: 20
              timeoutSeconds: 3
              failureThreshold: 3
            readinessProbe:
              enabled: false
            startupProbe:
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 3
              failureThreshold: 60
            extraEnvVars:
              - name: MINIO_REGION
                value: ap-southeast-1
              - name: MINIO_REGION_NAME
                value: ap-southeast-1
            ingress:
              enabled: true
              hostname: 'api-minio.{{ .Values.ingress.baseDomain }}'
              pathType: Prefix
              annotations:
                gethomepage.dev/enabled: "true"
                gethomepage.dev/name: "MinIO API"
                gethomepage.dev/group: "Storage"
                gethomepage.dev/icon: "minio.png"
                gethomepage.dev/ping: "https://api-minio.{{ .Values.ingress.baseDomain }}"
            persistence:
              enabled: true
              annotations:
                argocd.argoproj.io/sync-options: Delete=false,Prune=false
            defaultInitPermissions:
              volumePermissions:
                enabled: true
                image:
                  repository: bitnamilegacy/os-shell
                  tag: 12-debian-12-r50
            metrics:
              enabled: true
              serviceMonitor:
                enabled: true
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: kubernetes.io/arch
                          operator: NotIn
                          values: [ arm64, arm ]
            console:
              image:
                repository: bitnamilegacy/minio-object-browser
                tag: 2.0.2-debian-12-r3
              ingress:
                enabled: true
                hostname: 'minio.{{ .Values.ingress.baseDomain }}'
                pathType: Prefix
                annotations:
                  gethomepage.dev/enabled: "true"
                  gethomepage.dev/name: "MinIO"
                  gethomepage.dev/group: "Storage"
                  gethomepage.dev/icon: "minio.png"
                  gethomepage.dev/ping: "https://minio.{{ .Values.ingress.baseDomain }}"
              extraEnvVars:
                - name: MINIO_REGION
                  value: ap-southeast-1
                - name: MINIO_REGION_NAME
                  value: ap-southeast-1
              pdb:
                create: true
                minAvailable: 1
              autoscaling:
                hpa:
                  enabled: true
                  minReplicas: 2
                  maxReplicas: 5
                  targetCPU: 80
                  targetMemory: 80
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                      - matchExpressions:
                          - key: kubernetes.io/arch
                            operator: NotIn
                            values: [ arm64, arm ]
  destination:
    server: {{ .Values.destination.server }}
    namespace: minio
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
