{{- if not .Values.disableMinio }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: {{ include "apps.argocdNamespace" . | quote }}
  finalizers:
    {{- include "apps.finalizers" . | nindent 4 }}
spec:
  project: {{ .Values.project }}
  source:
    repoURL: https://operator.min.io
    chart: minio-operator
    targetRevision: 4.3.7
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            operator:
              replicaCount: 3
            console:
              ingress:
                enabled: true
                annotations:
                  gethomepage.dev/enabled: "true"
                  gethomepage.dev/name: "MinIO"
                  gethomepage.dev/group: "Storage"
                  gethomepage.dev/icon: "minio.png"
                  gethomepage.dev/ping: "https://minio.lab.kvd.studio"
                host: minio.lab.kvd.studio
            tenants:
              - name: minio1
                namespace: minio
                pools:
                  - servers: 4
                    volumesPerServer: 4
                    size: 64Gi
                secrets:
                  enabled: true
                  name: minio1-secret
                  accessKey: "<path:kv/data/lab/minio#ACCESS_KEY>"
                  secretKey: "<path:kv/data/lab/minio#SECRET_KEY>"
                metrics:
                  enabled: true
  destination:
    server: {{ .Values.destination.server }}
    namespace: minio
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
