{{- if not .Values.disableMinio }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: {{ include "apps.argocdNamespace" . | quote }}
  finalizers:
    {{- include "apps.finalizers" . | nindent 4 }}
spec:
  project: {{ .Values.project }}
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 14.7.0
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            image:
              tag: 2024.10.13-debian-12-r0
            mode: distributed
            auth:
              rootUser: '<path:kv/data/lab/minio#ROOT_USERNAME>'
              rootPassword: '<path:kv/data/lab/minio#ROOT_PASSWORD>'
            statefulset:
              replicaCount: 4
              zones: 1
              drivesPerNode: 4
            livenessProbe:
              enabled: true
              initialDelaySeconds: 20
              periodSeconds: 20
              timeoutSeconds: 3
              failureThreshold: 3
            readinessProbe:
              enabled: false
            startupProbe:
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 3
              failureThreshold: 60
            ingress:
              enabled: true
              hostname: 'minio.{{ .Values.ingress.baseDomain }}'
              path: /
              pathType: Prefix
              annotations:
                gethomepage.dev/enabled: "true"
                gethomepage.dev/name: "MinIO"
                gethomepage.dev/group: "Storage"
                gethomepage.dev/icon: "minio.png"
                gethomepage.dev/ping: "https://minio.{{ .Values.ingress.baseDomain }}"
            apiIngress:
              enabled: true
              hostname: 'api-minio.{{ .Values.ingress.baseDomain }}'
              path: /
              pathType: Prefix
            persistence:
              enabled: true
              annotations:
                argocd.argoproj.io/sync-options: Delete=false,Prune=false
            volumePermissions:
              enabled: true
            metrics:
              enabled: true
              serviceMonitor:
                enabled: true
  destination:
    server: {{ .Values.destination.server }}
    namespace: minio
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
