{{- if not .Values.disablePaperless }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless
  namespace: {{ include "apps.argocdNamespace" . | quote }}
  finalizers:
    {{- include "apps.finalizers" . | nindent 4 }}
spec:
  project: {{ .Values.project }}
  source:
    repoURL: https://charts.gabe565.com
    chart: paperless-ngx
    targetRevision: 0.18.0
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            env:
              PAPERLESS_SECRET_KEY: "<path:kv/data/lab/paperless#PAPERLESS_SECRET_KEY>"
            ingress:
              enabled: true
              annotations:
                gethomepage.dev/enabled: "true"
                gethomepage.dev/name: "Paperless"
                gethomepage.dev/group: "Finances"
                gethomepage.dev/icon: "paperless.png"
                gethomepage.dev/ping: "paperless.{{ .Values.ingress.baseDomain }}"
              hosts:
                - host: "paperless.{{ .Values.ingress.baseDomain }}"
                  paths:
                    - path: /
            persistence:
              data:
                enabled: true
              media:
                enabled: true
            postgresql:
              enabled: true
              auth:
                postgresPassword: "<path:kv/data/lab/paperless#POSTGRESQL_PASSWORD>"
              primary:
                persistence:
                  enabled: true
            redis:
              auth:
                enabled: false
              master:
                persistence:
                  enabled: true
  destination:
    server: {{ .Values.destination.server }}
    namespace: paperless
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
