{{- if not .Values.disablePlane }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plane
  namespace: {{ include "apps.argocdNamespace" . | quote }}
  finalizers:
    {{- include "apps.finalizers" . | nindent 4 }}
spec:
  project: {{ .Values.project }}
  source:
    repoURL: https://helm.plane.so/
    chart: plane-ce
    targetRevision: 1.4.1
    helm:
      releaseName: plane
      valuesObject:
        planeVersion: v1.2.0
        ingress:
          enabled: true
          appHost: "plane.{{ .Values.ingress.baseDomain }}"
          ingressClass: traefik
          ingress_annotations:
            gethomepage.dev/enabled: "true"
            gethomepage.dev/name: "Plane"
            gethomepage.dev/group: "Admin"
            gethomepage.dev/icon: "plane.png"
            gethomepage.dev/ping: "plane.{{ .Values.ingress.baseDomain }}"
        redis:
          storageClass: nfs-client
        postgres:
          local_setup: false
        minio:
          local_setup: false
        rabbitmq:
          storageClass: nfs-client
        external_secrets:
          rabbitmq_existingSecret: plane-secrets
          pgdb_existingSecret: plane-secrets
          doc_store_existingSecret: plane-secrets
          app_env_existingSecret: plane-secrets
          live_env_existingSecret: plane-secrets
  destination:
    server: {{ .Values.destination.server }}
    namespace: plane
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
