{{- if not .Values.disablePlane }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plane
  namespace: {{ include "apps.argocdNamespace" . | quote }}
  finalizers:
    {{- include "apps.finalizers" . | nindent 4 }}
spec:
  project: {{ .Values.project }}
  source:
    repoURL: https://helm.plane.so/
    chart: plane-ce
    targetRevision: 1.0.28
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            ingress:
              enabled: true
              appHost: plane.{{ .Values.ingress.baseDomain }}
              minioHost: plane-minio.{{ .Values.ingress.baseDomain }}
              ingressClass: traefik
              ingress_annotations:
                gethomepage.dev/enabled: "true"
                gethomepage.dev/name: "Plane"
                gethomepage.dev/group: "Admin"
                gethomepage.dev/icon: "plane.png"
                gethomepage.dev/ping: "plane.{{ .Values.ingress.baseDomain }}"
            redis:
              storageClass: nfs-client
            postgres:
              local_setup: false
            minio:
              local_setup: false
            env:
              pgdb_remote_url: "postgres://plane:<path:kv/data/lab/plane#POSTGRESQL_PASSWORD>@srv-pg-01.lab:5432/plane"
              aws_access_key: "<path:kv/data/lab/plane#MINIO_ROOT_USER>"
              aws_secret_access_key: "<path:kv/data/lab/plane#MINIO_ROOT_PASSWORD>"
              aws_s3_endpoint_url: "http://minio.minio.svc.cluster.local:9000"
              docstore_bucket: "plane"
              doc_upload_size_limit: "10485760"
              secret_key: "<path:kv/data/lab/plane#SECRET_KEY>"
  destination:
    server: {{ .Values.destination.server }}
    namespace: plane
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
