{{- if not .Values.disablePlausible }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plausible
  namespace: {{ include "apps.argocdNamespace" . | quote }}
  finalizers:
    {{- include "apps.finalizers" . | nindent 4 }}
spec:
  project: {{ .Values.project }}
  source:
    repoURL: https://git.lab.kvd.studio/r/homelab.git
    targetRevision: main
    path: plausible
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            env:
              - name: BASE_URL
                value: "https://plausible.{{ .Values.ingress.baseDomain }}"
  destination:
    server: {{ .Values.destination.server }}
    namespace: plausible
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
