{{- if not .Values.disableSonarqube }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: {{ include "apps.argocdNamespace" . | quote }}
  finalizers:
    {{- include "apps.finalizers" . | nindent 4 }}
spec:
  project: {{ .Values.project }}
  source:
    repoURL: https://SonarSource.github.io/helm-chart-sonarqube
    chart: sonarqube
    targetRevision: 10.4.1
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            ingress:
              enabled: true
              hosts:
                - name: sonarqube.{{ .Values.ingress.baseDomain }}
              annotations:
                gethomepage.dev/enabled: "true"
                gethomepage.dev/name: "Sonarqube"
                gethomepage.dev/group: "CI/CD"
                gethomepage.dev/icon: "sonarqube.png"
                gethomepage.dev/ping: "sonarqube.{{ .Values.ingress.baseDomain }}"
            prometheusExporter:
              enabled: true
            prometheusMonitoring:
              podMonitor:
                enabled: true
            persistence:
              enabled: true
  destination:
    server: {{ .Values.destination.server }}
    namespace: sonarqube
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
