{{- if not .Values.disableSupabase }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supabase
  namespace: {{ include "apps.argocdNamespace" . | quote }}
  finalizers:
      {{- include "apps.finalizers" . | nindent 4 }}
spec:
  project: {{ .Values.project }}
  source:
    repoURL: https://github.com/supabase-community/supabase-kubernetes.git
    targetRevision: main
    path: charts/supabase
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            secret:
              jwt:
                anonKey: "<path:kv/data/lab/supabase#ANON_JWT>"
                serviceKey: "<path:kv/data/lab/supabase#SERVICE_JWT>"
                secret: "<path:kv/data/lab/supabase#SECRET_JWT>"
              smtp:
                username: "<path:kv/data/lab/supabase#SMTP_USERNAME>"
                password: "<path:kv/data/lab/supabase#SMTP_PASSWORD>"
              dashboard:
                username: "<path:kv/data/lab/supabase#DASHBOARD_USERNAME>"
                password: "<path:kv/data/lab/supabase#DASHBOARD_PASSWORD>"
              analytics:
                apiKey: "<path:kv/data/lab/supabase#ANALYTICS_API_KEY>"
              db:
                username: postgres
                password: "<path:kv/data/lab/supabase#POSTGRESQL_PASSWORD>"
                database: supabase
            db:
              image:
                tag: 15.6.1.132
              persistence:
                enabled: true
              autoscaling:
                enabled: false
            studio:
              environment:
                STUDIO_DEFAULT_ORGANIZATION: KVD Studio
                STUDIO_DEFAULT_PROJECT: Supabase
                SUPABASE_PUBLIC_URL: "https://supabase.{{ .Values.ingress.baseDomain }}"
              autoscaling:
                enabled: false
            auth:
              image:
                tag: v2.163.0
              environment:
                DB_USER: postgres
                API_EXTERNAL_URL: "https://supabase.{{ .Values.ingress.baseDomain }}"
                GOTRUE_SITE_URL: "https://supabase.{{ .Values.ingress.baseDomain }}"
                GOTRUE_SMTP_ADMIN_EMAIL: "<path:kv/data/lab/supabase#SMTP_USERNAME>"
                GOTRUE_SMTP_HOST: smtp.gmail.com
                GOTRUE_SMTP_PORT: "587"
                GOTRUE_SMTP_SENDER_NAME: "<path:kv/data/lab/supabase#SMTP_USERNAME>"
              autoscaling:
                enabled: false
            rest:
              environment:
                DB_USER: postgres
              autoscaling:
                enabled: false
            realtime:
              environment:
                DB_USER: postgres
              autoscaling:
                enabled: false
            meta:
              environment:
                DB_USER: postgres
              image:
                tag: v0.84.2
              autoscaling:
                enabled: false
            storage:
              environment:
                DB_USER: postgres
              autoscaling:
                enabled: false
              persistence:
                enabled: true
            imgproxy:
              autoscaling:
                enabled: false
              persistence:
                enabled: true
            kong:
              ingress:
                enabled: true
                className: traefik
                annotations:
                  gethomepage.dev/enabled: "true"
                  gethomepage.dev/name: "Supabase"
                  gethomepage.dev/group: "CI/CD"
                  gethomepage.dev/icon: "si-supabase"
                  gethomepage.dev/ping: "https://supabase.{{ .Values.ingress.baseDomain }}"
                hosts:
                  - host: "supabase.{{ .Values.ingress.baseDomain }}"
                    paths:
                      - path: /
                        pathType: Prefix
            environment:
              KONG_PLUGINS: request-transformer,cors,key-auth,acl
            autoscaling:
                enabled: false
            analytics:
              environment:
                DB_USERNAME: postgres
              autoscaling:
                enabled: false
            vector:
              image:
                tag: latest-alpine
              autoscaling:
                enabled: false
            functions:
              image:
                tag: v1.59.0
              environment:
                DB_USERNAME: postgres
              autoscaling:
                enabled: false
  destination:
    server: {{ .Values.destination.server }}
    namespace: supabase
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
