{{- if not .Values.disableSuperset }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: {{ include "apps.argocdNamespace" . | quote }}
  finalizers:
    {{- include "apps.finalizers" . | nindent 4 }}
spec:
  project: {{ .Values.project }}
  source:
    repoURL: https://apache.github.io/superset
    chart: superset
    targetRevision: 0.12.11
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            configOverrides:
              secret: |
                SECRET_KEY = "<path:kv/data/lab/superset#SECRET_KEY>"
            extraEnvRaw:
              - name: DB_PASS
                value: "<path:kv/data/lab/superset#POSTGRESQL_PASSWORD>"
            init:
              createAdmin: true
              adminUser:
                username: "<path:kv/data/lab/superset#ADMIN_USERNAME>"
                firstname: Kenneth
                lastname: Domingo
                email: "<path:kv/data/lab/superset#ADMIN_EMAIL>"
                password: "<path:kv/data/lab/superset#ADMIN_PASSWORD>"
            image:
              repository: apache/superset
              tag: 3.1.1
            ingress:
              enabled: true
              annotations:
                gethomepage.dev/enabled: "true"
                gethomepage.dev/name: "Superset"
                gethomepage.dev/group: "Analytics"
                gethomepage.dev/icon: "superset.png"
                gethomepage.dev/ping: "superset.{{ .Values.ingress.baseDomain }}"
              pathType: Prefix
              hosts:
                - superset.{{ .Values.ingress.baseDomain }}
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 256Mi
            supersetNode:
              autoscaling:
                enabled: true
                minReplicas: 2
                maxReplicas: 5
                targetCPUUtilizationPercentage: 80
              podDisruptionBudget:
                enabled: true
                minAvailable: 2
                maxUnavailable: ~
              connections:
                db_pass: "<path:kv/data/lab/superset#POSTGRESQL_PASSWORD>"
            supersetWorker:
              autoscaling:
                enabled: true
                minReplicas: 2
                maxReplicas: 5
                targetCPUUtilizationPercentage: 80
              podDisruptionBudget:
                enabled: true
                minAvailable: 2
                maxUnavailable: ~
            supersetCeleryBeat:
              enabled: true
              podDisruptionBudget:
                enabled: true
                minAvailable: 2
                maxUnavailable: ~
            postgresql:
              auth:
                password: "<path:kv/data/lab/superset#POSTGRESQL_PASSWORD>"
            redis:
              architecture: replication
              master:
                persistence:
                  enabled: true
  destination:
    server: {{ .Values.destination.server }}
    namespace: superset
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
