{{- if not .Values.disableTimeMachine }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: time-machine
  namespace: {{ include "apps.argocdNamespace" . | quote }}
  finalizers:
    {{- include "apps.finalizers" . | nindent 4 }}
spec:
  project: {{ .Values.project }}
  source:
    repoURL: https://github.com/kvdomingo/homelab-automation.git
    targetRevision: main
    path: time-machine
    plugin:
      name: argocd-vault-plugin-helm
  destination:
    server: {{ .Values.destination.server }}
    namespace: time-machine
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
