{{- if not .Values.disableUnreceiptify }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unreceiptify
  namespace: {{ include "apps.argocdNamespace" . | quote }}
  finalizers:
    {{- include "apps.finalizers" . | nindent 4 }}
spec:
  project: {{ .Values.project }}
  source:
    repoURL: https://github.com/kvdomingo/unreceiptify.git
    targetRevision: main
    path: infra/helm/unreceiptify
  destination:
    server: {{ .Values.destination.server }}
    namespace: unreceiptify
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
