{{- if not .Values.disableZitadel }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zitadel
  namespace: {{ include "apps.argocdNamespace" . | quote }}
  finalizers:
    {{- include "apps.finalizers" . | nindent 4 }}
spec:
  project: {{ .Values.project }}
  sources:
    - repoURL: https://charts.zitadel.com
      chart: zitadel
      targetRevision: 8.5.0
      plugin:
        name: argocd-vault-plugin-helm
        env:
          - name: HELM_VALUES
            value: |
              zitadel:
                configMapConfig:
                  ExternalSecure: true
                  ExternalPort: 443
                  ExternalDomain: "zitadel.{{ .Values.ingress.baseDomain }}"
                  TLS:
                    Enabled: false
                  Machine:
                    Identification:
                      Hostname:
                        Enabled: true
                      Webhook:
                        Enabled: false
                  Database:
                    cockroach:
                      Host: crdb
                masterkey: "<path:kv/data/lab/zitadel#MASTER_KEY>"
              replicaCount: 3
              ingress:
                enabled: true
                annotations:
                  gethomepage.dev/enabled: "true"
                  gethomepage.dev/name: "Zitadel"
                  gethomepage.dev/group: "Admin"
                  gethomepage.dev/icon: "zitadel.png"
                  gethomepage.dev/ping: "zitadel.{{ .Values.ingress.baseDomain }}"
                hosts:
                  - host: zitadel.{{ .Values.ingress.baseDomain }}
                    paths:
                      - path: /
                        pathType: Prefix
              metrics:
                enabled: true
                serviceMonitor:
                  enabled: true
                  honorLabels: true
              pdb:
                enabled: true
                minAvailable: 2
    - repoURL: https://charts.cockroachdb.com/
      chart: cockroachdb
      targetRevision: 14.0.4
      plugin:
        name: argocd-vault-plugin-helm
        env:
          - name: HELM_VALUES
            value: |
              fullnameOverride: crdb
              store:
                enabled: true
                type: empty
              statefulset:
                replicas: 3
                budget:
                  maxUnavailable: 1
                resources:
                  limits:
                    cpu: 100m
                    memory: 512Mi
              prometheus:
                enabled: true
              serviceMonitor:
                enabled: true
              tls:
                enabled: false
                certs:
                  selfSigner:
                    enabled: false
  destination:
    server: {{ .Values.destination.server }}
    namespace: zitadel
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
