apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-kvd-studio-cert
spec:
  secretName: dev-kvd-studio-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.dev.kvd.studio"
  dnsNames:
    - dev.kvd.studio
    - "*.dev.kvd.studio"
