apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "<path:kv/data/lab/cloudflare#CLOUDFLARE_EMAIL>"
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          cloudflare:
            email: "<path:kv/data/lab/cloudflare#CLOUDFLARE_EMAIL>"
            apiKeySecretRef:
              name: cloudflare-secrets
              key: CLOUDFLARE_API_KEY
        selector:
          dnsZones:
            - kvd.studio
            - banyuh.ai
