apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-secrets
  labels:
    app.kubernetes.io/part-of: cert-manager
  annotations:
    avp.kubernetes.io/path: kv/data/lab/cloudflare
type: Opaque
stringData:
  CLOUDFLARE_API_KEY: "<CLOUDFLARE_API_KEY>"
  CLOUDFLARE_EMAIL: "<CLOUDFLARE_EMAIL>"
