repositories:
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: promstack
    namespace: monitoring
    chart: prometheus/kube-prometheus-stack
    version: 66.2.2
    values:
      - ./values.yaml
      - alertmanager:
          config:
            receivers:
              - name: discord
                discord_configs:
                  - webhook_url: ref+vault://kv/lab/promstack#DISCORD_WEBHOOK_URL
        grafana:
          adminPassword: !!string ref+vault://kv/lab/promstack#GRAFANA_PASSWORD
