repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: manifests
    namespace: monitoring
    chart: ./manifests
  - name: promstack
    namespace: monitoring
    chart: bitnami/kube-prometheus
    version: 9.6.2
    values:
      - promstack-values.yaml
  - name: loki
    namespace: monitoring
    chart: grafana/loki
    version: 6.15.0
    values:
      - loki-values.yaml
  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    version: 8.5.1
    values:
      - grafana-values.yaml
