apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: kimai-inf-secret
  labels: { }
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  syncConfig:
    resyncInterval: 10s
  authentication:
    kubernetesAuth:
      identityId: ea9c7e43-4921-4cac-bac7-8fc8b1a24440
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: infisical2
      secretsScope:
        projectSlug: kimai
        envSlug: prod
        secretsPath: /
        recursive: true
  managedKubeSecretReferences:
    - secretName: kimai-secrets
      secretNamespace: kimai
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        metadata:
          annotations:
            helm.sh/hook: pre-install
            helm.sh/hook-weight: "-5"
            helm.sh/hook-delete-policy: before-hook-creation
        data:
          app-secret: "{{ .APP_SECRET.Value }}"
          admin-password: "{{ .ADMIN_PASSWORD.Value }}"
          mailer-url: "{{ .MAILER_URL.Value }}"
          mariadb-root-password: "{{ .MARIADB_ROOT_PASSWORD.Value }}"
          mariadb-replication-password: "{{ .MARIADB_REPLICATION_PASSWORD.Value }}"
          mariadb-password: "{{ .MARIADB_PASSWORD.Value }}"
          database-url: "mariadb://kimai:{{ .MARIADB_PASSWORD.Value }}@kimai-mariadb:3306/kimai"
