apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "primerdriver.fullname" . }}-configmap"
  labels:
    {{- include "primerdriver.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  PORT: "{{ .Values.service.port }}"
